cerner/terra-framework

- packages/terra-framework-site/package.json
- packages/terra-framework-site/postcss.config.js
- packages/terra-framework-site/webpack.config.js
* add postcssassets-plugin
This enables us to compile themes using the `:root` selector to static values for testing theming in browsers that lack support for CSS custom properties.
Sync with core https://github.com/cerner/terra-core/pull/971
@cerner/terra
> Add postcssassets-plugin

- package.json
- packages/terra-application-header-layout/.npmignore
- packages/terra-application-menu-layout/.npmignore
- packages/terra-framework-site/.npmignore
- packages/terra-layout/.npmignore
- packages/terra-navigation-layout/.npmignore
- scripts/post-install/index.js
* Adding `src` and `tests` directories to npm packages so we can access them in the theme repos.
* Updated postinstall script to be able to detect in what situation it is being run in. (npm install in monorepo vs installing monorepo into another project)
> Update repo to use with theme repo

- .travis.yml
- package.json
Two days ago docker-selenium [released a new version](https://github.com/SeleniumHQ/docker-selenium/commit/cfc1eeb5cdcea02395016685d7012688768ed342) of both selenium/node-chrome and selenium/standalone-chrome. In our tests we pull in the latest tag of both.
The previous version is `3.8.1-erbium` and the latest release is `3.8.1-francium`. 
This pulls the previous version to see if this resolves the issues we are seeing with the repeated
` Expected element ' ' to be present - element was not found`
> Lock Down docker-selenium Version

- .travis.yml
The site directory doesn't exist. So I think this should fix it
> Fix Travis Deploy

- README.md
Emoji do not render in our static deployed site. This PR replaces the status emoji with shields (which are externally hosted) to keep the read me consistent across deployments of the site.
@cerner/terra
> Replace status emoji with shields.

- .gitignore
- package.json
- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/examples/test-examples/LayoutLongText.jsx
- wdio.conf.js
Add base configuration of web driver to the framework package.
@cerner/terra
> Add weddriver.io test functionality

- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/tests/jest/__snapshots__/Layout.test.jsx.snap
Ezyme-to-json 3.3.1 removed defaulted values set in props, so we need to regenerate our snapshots.
@cerner/terra
> Update snapshots tests to match new default pattern updated by enzyme.

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/docs/README.md
Little bug fix for the docs. `requestFocus` was listed incorrectly for `releaseFocus` documentation.
> Correct disclosure manager documentation

- CONTRIBUTORS.md
- packages/terra-slide-panel/CHANGELOG.md
- packages/terra-slide-panel/src/SlidePanel.scss
- themeable-variables.json
These changes will allow the Slide Panel Background to accept the 'fallback syntax' and accept a variable for the background color.
Fixes Issue #140
> Allow Slide Panel Background to be Themeable

- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/src/tabs/ApplicationTabs.scss
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/src/MenuItem.scss
This change resolves the aXe tests erroneously logging contrast issues as the background color now get's set on a DOM element instead of the pseudo-element. Styles for background-image have been left on the pseudo-element to work around layering issue with background-images and focus styles.
> Update themable background styles on selectable menu items in navigation

- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/src/NotificationDialog.jsx
- packages/terra-notification-dialog/src/terra-dev-site/test/notification-dialog/NotificationDialogVariant.test.jsx
Fixed the naming of the aria label prop being passed down from `NotificationDialog` to `AbstractModal`.
Closes #207.
In addition, there was a propType warning for one of the tests. The `propType.oneOf` was being passed an object instead of an array.
@cerner/terra
> Fixed ariaLabel props in NotificationDialog

- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalWithCustomHeaderAndCustomFooter.jsx
- packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DialogModalWithCustomHeaderAndCustomFooter.test.jsx
Fix webpack issue due to referencing src instead of a relative path which would end up hitting lib which has been transpiled.
> Fix webpack issue due to referencing src instead of a relative path

- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DefaultDialogModal.test.jsx
- packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DialogModalWithLongText.test.jsx
Fixing relative references in the test files of terra-dialog-modal
> Fixing relative references in the test files of terra-dialog-modal

- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/src/NotificationDialog.scss
`initial` values are not supported by Internet Explorer so it was changed to it's equivalent.
Sync with https://github.com/cerner/terra-core/issues/1667 
@cerner/terra 
Deployment Link
https://terra-framework-deploye-pr-218.herokuapp.com/#/components/terra-notification-dialog/notification-dialog/notification-dialog
> Remove CSS 'initial' Value

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-application-header-layout/src/terra-dev-site/doc/example/HeaderWireframe.jsx
- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/package.json
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
Missed bumping these to new major version in last update. This corrects the version so using the latest release of terra-ui components will all use terra-responsive-element v3.
> Bump responsive-element version

- packages/terra-application-layout/docs/usage.md
The ApplicationLayout example was using the BrowserRouter, which requires some server-side configuration to properly work. We use the HashRouter for terra-dev-site, and I've updated the example to use the HashRouter as well.
> Update ApplicationLayout documentation for clarity around expected react-router usage

- packages/terra-brand-footer/CHANGELOG.md
- packages/terra-brand-footer/src/BrandFooter.jsx
- packages/terra-brand-footer/src/BrandFooter.module.scss
- packages/terra-brand-footer/tests/jest/__snapshots__/BrandFooter.test.jsx.snap
Resolves #254
Brand Footer Lists were difficult to read with screen readers, as the heading was part of the list. This pull request puts the links in their own separate list, and then places that inside a section complete with a header.
> Make Branding Footer Markup more Accessible

- packages/terra-aggregator/tests/wdio/aggregator-spec.js
- packages/terra-application-header-layout/tests/wdio/application-header-spec.js
- packages/terra-application-layout/tests/wdio/application-header-spec.js
- packages/terra-application-layout/tests/wdio/application-layout-spec.js
- packages/terra-application-layout/tests/wdio/application-menu-spec.js
- packages/terra-application-layout/tests/wdio/routing-menu-spec.js
- packages/terra-application-links/tests/wdio/application-tabs-spec.js
- packages/terra-application-menu-layout/tests/wdio/application-menu-spec.js
- packages/terra-application-name/tests/wdio/application-header-name-spec.js
- packages/terra-application-name/tests/wdio/application-menu-name-spec.js
- packages/terra-application-utility/tests/wdio/application-header-utility-spec.js
- packages/terra-application-utility/tests/wdio/application-menu-utility-spec.js
- packages/terra-application-utility/tests/wdio/header-utility-menu-spec.js
- packages/terra-application-utility/tests/wdio/menu-utility-menu-spec.js
- packages/terra-brand-footer/tests/wdio/brand-footer-spec.js
- packages/terra-dialog-modal/tests/wdio/dialog-modal-spec.js
- packages/terra-hookshot/tests/wdio/hookshot-combinations-spec.js
- packages/terra-hookshot/tests/wdio/hookshot-spec.js
- packages/terra-infinite-list/tests/wdio/infinite-list-spec.js
- packages/terra-layout/tests/wdio/layout-slide-panel-spec.js
- packages/terra-modal-manager/tests/wdio/modal-manager-spec.js
- packages/terra-navigation-layout/tests/wdio/navigation-layout-spec.js
- packages/terra-navigation-side-menu/tests/wdio/navigation-side-menu-spec.js
- packages/terra-notification-dialog/tests/wdio/notification-dialog-spec.js
- packages/terra-popup/tests/wdio/popup-spec.js
- packages/terra-slide-panel-manager/tests/wdio/slide-panel-manager-spec.js
- packages/terra-slide-panel/tests/wdio/slide-panel-spec.js
- packages/terra-theme-provider/tests/wdio/theme-provider-spec.js
eslint-config module defines before, browser, and Terra as globals for test files recursively under a "wdio" directory
> Clean up un-needed globals

- CONTRIBUTORS.md
- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/package.json
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/package.json
Removed any instances where terra-base was listed as both a peerDependency and either a dependency or devDependency (kept it as a peerDependency).
Closes [#200](https://github.com/cerner/terra-framework/issues/200)
> Removed duplicate terra-base dependencies

- packages/terra-application-header-layout/CHANGELOG.md
- packages/terra-application-header-layout/package.json
- packages/terra-application-header-layout/src/ApplicationHeaderLayout.jsx
This is related to https://github.com/cerner/terra-core/issues/1982
This update pulls in react-intl modules directly from react-intl instead of terra-base. When pulling the modules from terra-base, it was pulling in more code and executing more code than just the react-intl modules that were specified.
> Update intl imports in header layout

- jestconfig.js
Added a fix to jestconfig.js in root directory to allow for Jest tests to properly run on Windows.
Resolves [#224](https://github.com/cerner/terra-framework/issues/224)
> Windows fix for Jest test error

- .travis.yml
- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/src/HookshotContent.jsx
Using `npm run danger; npm run lint; npm run jest` instead of `npm run danger && npm run lint && npm run jest` doesn't fail the build. The `;` will execute the next script regardless of exit code.
> Fix travis & Fix lint error

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/tests/wdio/aggregator-spec.js
Removes the local timeouts from wdio tests in favor of global timer.
Closes [cerner/terra-core#1756](https://github.com/cerner/terra-core/issues/1756)
> Update Wdio Test Timeouts

- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
We [added a fallback behavior to how focus trap works in abstract modal](https://github.com/cerner/terra-core/pull/2112) which has triggered a jest snapshot failure in framework.
> Update jest snapshot

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/src/user/UserData.module.scss
There are instances where the UserData stylesheet is loaded twice. This causes issues in the examples, where we pass in an Avatar component. 
In some cases, the style load order is `UserData`->`Avatar`->`UserData`. In other cases, the style load order is `UserData`->`Avatar`. 
This change increases specificity of the `photo` class. Now, UserData photo styles will always override Avatar styles. This will make builds stable for now, but we still need to dig into the root of this issue.
> Increase UserData CSS Class Specificity

- .npmignore
- packages/terra-aggregator/.npmignore
- packages/terra-application-header-layout/.npmignore
- packages/terra-application-layout/.npmignore
- packages/terra-application-links/.npmignore
- packages/terra-application-menu-layout/.npmignore
- packages/terra-application-name/.npmignore
- packages/terra-application-utility/.npmignore
- packages/terra-brand-footer/.npmignore
- packages/terra-dialog-modal/.npmignore
- packages/terra-disclosure-manager/.npmignore
- packages/terra-embedded-content-consumer/.npmignore
- packages/terra-form-validation/.npmignore
- packages/terra-hookshot/.npmignore
- packages/terra-infinite-list/.npmignore
- packages/terra-layout/.npmignore
- packages/terra-modal-manager/.npmignore
- packages/terra-navigation-layout/.npmignore
- packages/terra-navigation-side-menu/.npmignore
- packages/terra-notification-dialog/.npmignore
- packages/terra-popup/.npmignore
- packages/terra-slide-group/.npmignore
- packages/terra-slide-panel-manager/.npmignore
- packages/terra-slide-panel/.npmignore
- packages/terra-theme-provider/.npmignore
- packages/terra-time-input/.npmignore
Adds .npmignore file to package to ignore extraneous directories.
Closes [#425](https://github.com/cerner/terra-framework/issues/425)
> Add .npmignore to Package

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/package.json
I'm removing the dependencies that are no longer being used by the package. They were once used by the disclosure manager's examples, but those examples were removed some time ago.
This should result in fewer major version bumps to the package going forward.
> [terra-disclosure-manager] Removing unused dependencies

- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItemGroup.jsx
- packages/terra-collapsible-menu-view/tests/jest/__snapshots__/CollapsibleMenuViewItemGroup.test.jsx.snap
Wrapped the CollapsibleMenuItems in li tags. Also ensured that doing so would not add any extra spacing (see before & after screenshot).
Resolves [#396](https://github.com/cerner/terra-framework/issues/396)
> Wrapped collapsible menu items in <li> tags

- CONTRIBUTORS.md
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
- packages/terra-date-time-picker/src/DateTimeUtils.js
- packages/terra-date-time-picker/tests/jest/DateTimePicker.test.jsx
Resolves the NPE error when user tries to enter time along with valid date outside of the allotted datetime range.
The fix is to validate whether the date entered is within the datetime range after the date value is validated.
Resolves #2074
>  Fixes issue #2074 DatetimePicker throws NPE if manually entered valid datetime is outside of allotted datetime range

- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/src/Hookshot.jsx
- packages/terra-hookshot/src/HookshotContent.jsx
Add behavior to disable onclickoutside if the callback isn't passed.
Validation of the the select fix can be done on the hookshot doc page. There is currently a circular dependency on form select, long term this should be corrected, but in the short term it can be used.
@cerner/terra
> [terra-hookshot] Add behavior to disable onclickoutside if the callback isn't passed.

- CONTRIBUTORS.md
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
The terra-heading dependency is no longer being used in terra-modal-manager and can be removed. Closes #531
> Remove terra-heading dependency from terra-modal-manager

- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/src/terra-dev-site/doc/example/ContentComponent.jsx
- packages/terra-slide-panel-manager/src/terra-dev-site/doc/example/SlidePanelManagerExample.jsx
The doc page for the slide-panel-manager component examples were using duplicate id's which raised a red flag for accessibility warnings, so I made the id's unique for each example.
Resolves [#508](https://github.com/cerner/terra-framework/issues/508)
> Updated doc page to remove duplicate ids

- package.json
Update link-parent-bin to latest stable release.
This should resolve the npm deprecation warning we see on install for this project:
```
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
```
> Update link-parent-bin to latest stable release

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/src/terra-dev-site/test/common/ExtensionsExample.jsx
- packages/terra-application-layout/src/terra-dev-site/test/common/demoStyles.scss
- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/src/terra-dev-site/test/application-links/ApplicationTabsDefault.test.jsx
- packages/terra-application-links/src/terra-dev-site/test/application-links/demoStyles.scss
- packages/terra-application-name/CHANGELOG.md
- packages/terra-application-name/src/terra-dev-site/test/application-name/ApplicationHeaderNameDefault.test.jsx
- packages/terra-application-name/src/terra-dev-site/test/application-name/ApplicationHeaderNameTruncated.test.jsx
- packages/terra-application-name/src/terra-dev-site/test/application-name/ApplicationMenuNameWrapping.test.jsx
- packages/terra-application-name/src/terra-dev-site/test/application-name/demoStyles.scss
While working on a theme that changes the text color for some of the application components, noticed some accessibility errors from wdio/axe-core that the colors were not accessible. After looking into the wdio errors, found out that the text color was themable but it was placed on a hard-coded background color used in the wdio test files. 
This PR updates those hard-coded colors to be themable, allowing for the ability to theme them to complement if the text or background color for these components is also updated in a theme.
> Update demo styles to be themable

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/docs/README.md
- packages/terra-disclosure-manager/src/DisclosureManager.jsx
As of #583, the DisclosureManager will prevent dismissals of components disclosed without a key. A unique key is expected to be provided with the disclose request, per the documentation, and this was not expected to be a breaking change.
However, some consumers of the disclosure manager were **not** providing a key with their disclose requests. As of #583, this results in modals that can be opened but not closed. While I consider this a bug in their implementation, it is a regression in their functionality and leaves their applications in an unfortunate state.
This PR updates the documentation to be more explicit and removes the undefined check within the dismiss functions that is causing the above issue. I've logged #623 to better handle this in the future.
> [terra-disclosure-manager] Explicitly documenting the required arguments for the disclose behavior

- package.json
Updated terra-dev-site version in root package.json to:
`"terra-dev-site": "^4.0.0",`
Resolves [#616](https://github.com/cerner/terra-framework/issues/616)
> Terra-dev-site version update

- packages/terra-application-header-layout/CHANGELOG.md
- packages/terra-application-header-layout/src/ApplicationHeaderLayout.jsx
- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/src/_LayoutSlidePanel.jsx
- packages/terra-layout/tests/jest/__snapshots__/LayoutSlidePanel.test.jsx.snap
Resolves https://github.com/cerner/terra-core/issues/2322 partly.
The other part of the fix is in: https://github.com/cerner/terra-core/pull/2396
Edit: Tested the skip link navigation to the main content interaction with both JAWS/IE 11 and VoiceOver/Safari and it continues to work the same as prior to this change, correctly navigating the user to the main content when the user "clicks" on the skip to main content button.
> Update tabindex logic on main element

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/terra-dev-site/doc/example/DateTimePickerFilterDates.jsx
Fix js error in the filterDate example.
- Fixes #667 
- PR #590 changed the data type of the paramter in the filterDate callback from a moment object to a string. The filterDate example in terra-date-time-picker needs to be updated to handle this change.
@cerner/terra
> [terra-date-time-picker] Fixed js error in the filterDate example.

- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/package.json
- packages/terra-layout/src/LayoutUtils.js
- packages/terra-navigation-layout/CHANGELOG.md
- packages/terra-navigation-layout/package.json
- packages/terra-navigation-layout/src/NavigationLayout.jsx
- packages/terra-navigation-layout/tests/jest/__snapshots__/NavigationLayout.test.jsx.snap
Removes dependency on terra-responsive element. This update will make it easier for us to roll out the required non-passive change to terra-responsive-element.
> Remove responsive-element from terra-layout and terra-navigation-layout

- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationOnSubmit.jsx
Fixes https://github.com/cerner/terra-framework/issues/696.
The onSubmit example was using terra-select's 3.0.0 onChange function prop instead of 4.0.0.
onChange(event, value, name) -> onChange(value)
@cerner/terra
> [terra-form-validation] Fixing onSubmit example

- dangerfile.js
- packages/terra-time-input/src/TimeInput.jsx
The previous commit overhauling the danger file also updated danger's version. In some version danger stopped including two new lines before `warn` and `fail` messages. Removing those new lines causes the markdown to not be parsed correctly. Adding an empty line before the list starts causes the list to be displayed properly.
The change in effect: <img width="792" alt="Screen Shot 2019-06-04 at 1 33 54 PM" src="https://user-images.githubusercontent.com/11130785/58904586-71f7e580-86cd-11e9-9d98-31e8fcbf58c9.png">
> Fix danger message formatting

- package.json
DangerJS v8.0.0 was just released, updating to latest major version
> Update DangerJS to latest major version

- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
Updates terra-form-validation to allow it to pull in react-final-form v6. The current code in terra-form-validation is compatible with both v5 and v6 versions of react-final-form.
This will currently pull in react-final-form v6.2.1
> Update react-final-form dependency version range

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/package.json
- packages/terra-abstract-modal/src/AbstractModal.jsx
[The wicg-inert polyfill updated to use the same logic we were using to ensure that inert is not defined on the Element prototype before it tries to define that](https://github.com/WICG/inert/pull/123). With this change, we no longer need to conditionally load it and go back to a regular import statement. This also resolved the issue we had with this import when running it through Jest.
> Remove conditional logic around importing wicg-inert

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/AbstractModal.jsx
- packages/terra-abstract-modal/src/_contains-polyfill.js
Similar change to https://github.com/cerner/terra-core/commit/6fd60818bb20dfa00010c37752b59f46a6e0d2c5
Needed to support inert polyfill in IE10 / IE11
> Add node contains polyfill for IE10 / IE11 for abstract modal

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/tabs/Tab.module.scss
Corrected mislabeled themable variable that got past the lint rule.
@cerner/terra
> [terra-application-navigation] Fixed themable variable naming.

- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
The main key in the package.json file for the terra-form-validations package currently points to the README.md file. This updates the main key to point to the actual JS module the package contains in the lib directory.
Consumers noted running into errors when trying to use the Utils module via `import FormValidationUtil from 'terra-form-validation';`
> Update form validation main key

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DatePickerField.jsx
Update how we access the Error icon in terra-datepicker field.
> Explicitly pull in Error icon from terra-icon instead of pulling from terra-form-field

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/src/DisclosureManagerHeaderAdapter.jsx
Updating doc that didn't get changed during development. The consumer-facing documentation referenced the correct prop name, so this doesn't functionally impact anything.
> Update DisclosureManagerHeaderAdapter.jsx docs

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/tests/wdio/date-time-picker-spec.js
Few wdio tests were failing in theming repos(verified in fusion and clinical theme) with `element ("[class*="time-clarification"]") still not visible after 3000ms` error. Added browser.refresh() to support the test.
> [date-time-picker]Updated date-time-picker spec to support theming repos.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/ApplicationNavigation.jsx
- packages/terra-application-navigation/src/utils/helpers.js
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/src/DateInput.jsx
- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/src/DisclosureManagerHeaderAdapter.jsx
I noticed we had a few new eslint warnings around our current hooks implementations (and a random console log). This PR cleans those up.
> Fix lint warnings throughout terra-framework

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/AbstractModal.jsx
Fixes #901.
I was able to reproduce this when the modal is disclosed via a non-HTML element (SVG for example). In the test case below, `modalTrigger` is the SVG element (that does not support `focus()`) on IE but it is the `body` element on other major browsers. 
<details> <summary> Reduced Test Case </summary>
```
import React from 'react';
import PropTypes from 'prop-types';
import ContentContainer from 'terra-content-container';
import { withDisclosureManager, disclosureManagerShape } from 'terra-disclosure-manager';
import ModalManager from 'terra-modal-manager';
class DisclosureComponent extends React.Component {
constructor(props) {
super(props);
this.disclose = this.disclose.bind(this);
this.closeDisclosure = this.closeDisclosure.bind(this);
}
disclose(size, dimensions) {
const { …
```
> [terra-abstract-modal] Check whether `focus` is defined for the modal trigger element before restoring focus.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/wdio/application-navigation-spec.js
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/MenuItem.module.scss
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/src/NotificationDialog.module.scss
- Fix wdio test url in terra-application-navigation.
- Remove extra comma in scss files.
- The following error occurs in the clinical theme repo. The cause appears to be having an incorrect test url. I would expect the same test in terra-frame to fail but that's not the case. Not sure why it is only happening for the clinical theme. The header toggle button does appear in the clinical theme dev site.
```
1) [small] ApplicationNavigation - Small Nav drawer button should be displayed when only help, settings or logout utilities are present open drawer:
element ("[data-compact-header-toggle="true"]") still not visible after 3000ms
running chrome
Error: element ("[data-compact-header-toggle="true"]") still not visible after 3000ms
at elements("[data-compact-header-toggle="true"]") - …
```
> Fix wdio test url.

- CONTRIBUTORS.md
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/src/DialogModal.jsx
- packages/terra-dialog-modal/tests/jest/DialogModal.test.jsx
- packages/terra-dialog-modal/tests/jest/__snapshots__/DialogModal.test.jsx.snap
Ran into a problem where the root element is not being found and so the form is still tabbable when the modal is displaying because it doesn't add the inert attribute.
Found a relevant discussion here: https://github.com/cerner/terra-core/pull/2288/files#r269104366
Can we set a default in Base that will make this just work so we don't have to add this to every dialog box? Seems like this would be a pretty common mistake.
> [terra-dialog-modal] - Add rootSelector prop

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/jest/header/__snapshots__/Header.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenuHeaderButton.test.jsx.snap
Jest snapshots failing in master. Updated Jest snapshot due to changes in PR [#2762](https://github.com/cerner/terra-core/pull/2762/files) for terra-avatar.
> [terra-application-navigation]Updated Jest snapshots failing in master.

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/docs/README.md
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/docs/DatePickerField.md
- packages/terra-date-picker/docs/README.md
- packages/terra-slide-group/CHANGELOG.md
- packages/terra-slide-group/docs/README.md
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/docs/README.md
Remove yarn reference in docs. We don't support yarn first-class.
> Remove yarn ref in docs

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/ApplicationNavigation.module.scss
The change to a transparent background color impacts the ApplicationNavigation's menu animations at compact breakpoints.
We need to think about this background color change some more.
> Reverting a29151d25 (PR 1038) due to unintended animation changes

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/tests/wdio/date-picker-spec.js
The sizing of the date picker's input appears to result in the cursor to be placed one character over from where it does when clicking the input in the default theme. The ends up causing a `0` to remain in the input. Adding an extra backspace fixes this.
> [date-picker] Fix clinical-theme test

- packages/terra-theme-context/CHANGELOG.md
- packages/terra-theme-context/src/ThemeContextProvider.jsx
- packages/terra-theme-context/src/terra-dev-site/doc/ThemeContext/ThemeContext.1.doc.mdx
- packages/terra-theme-context/src/terra-dev-site/doc/example/ThemeContextProviderExample.jsx
- packages/terra-theme-context/src/terra-dev-site/doc/example/ThemedComponent.jsx
- packages/terra-theme-context/tests/jest/ThemeContextProvider.test.jsx
- packages/terra-theme-context/tests/jest/__snapshots__/ThemeContextProvider.test.jsx.snap
These changes allow a theme name to be set on the theme context
https://terra-framework-deploy-pr-1101.herokuapp.com/
Jest
The theme name will be `undefined` in this PR until this PR gets released and consumed in terra-framework. https://github.com/cerner/terra-toolkit-boneyard/pull/33
Related PRs:
https://github.com/cerner/terra-toolkit-boneyard/pull/33
https://github.com/cerner/terra-application/pull/35
@cerner/terra
> Allow theme name to be set on the theme context.

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-form-validation/src/terra-dev-site/doc/example/DefaultFormValidation.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/FormSubmitDatePicker.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/MaxLengthInput.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationAsynchronous.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationDisableSubmit.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationOnInput.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationOnSubmit.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationParsing.jsx
- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/package.json
- packages/terra-hookshot/src/terra-dev-site/doc/example/BoundedHookshotExample.jsx
- packages/terra-hookshot/src/terra-dev-site/doc/example/CoordsHookshotExample.jsx
- packages/terra-hookshot/src/terra-dev-site/doc/example/HookshotExample.jsx
Update Form Dependencies for:
- terra-aggregator
- terra-form-validation
- terra-hookshot
This also update a an error I saw in the hookshot doc examples when NaN was passed as a value to the form input when clearing the default input value.
Closes #1205 
- Project tests
@cerner/terra
> Update Form Dependenies

- package.json
eslint-config-terra now contains the dependency on babel-eslint and defaults it as our lint parser. we can remove those from this repo now.
Closes #1203 
@cerner/terra
> Remove babel-eslint dev dep

- CONTRIBUTORS.md
- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/src/terra-dev-site/doc/disclosure-manager/DisclosureManagerAPI.3.doc.mdx
- Changed 'size' to 'dimensions' in documentation.
Updating documentation to fix a typo.
Closes #1288
I only change one word.
@cerner/terra
> [terra-disclosure-manager] Issue-1228 Typo in API details

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/tests/wdio/date-time-picker-spec.js
Fix flaky tests.
Several tests use the `Tab` key to lose focus from the date/time input. It appears that there could be timing issues where tabbing away to lose focus and handling the blur takes slightly longer to complete. As a result, the assertion statement immediately after the Tab get execute too quickly and the expected text/value has not yet updated on the test page. Instead of using tab to blur, an alternative is to click on `#root`.
@cerner/terra
> Fix more flaky tests

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/common/_PopupMenu.jsx
- packages/terra-application-navigation/src/drawer-menu/_DrawerMenu.jsx
- packages/terra-application-navigation/tests/jest/__snapshots__/ApplicationNavigation.test.jsx.snap
Theme context was missing for the `_DrawerMenu` and the `_PopupMenu`, therefore making the application navigation popup menu and drawer menu appear to not be themed when dynamically switching themes with devsite. 
Closes #1394   _(originally [Terra-Application#133](https://github.com/cerner/terra-application/issues/133) )_
https://terra-framew-applicatio-68zdqb.herokuapp.com/components/terra-application-navigation/application-navigation/example
1. Go to deployment link
2. Change to lowlight-theme
3. Open User/Utilities Popup menu at large screen size
3. Open Navigation drawer at small screen size
@cerner/terra
> [terra-application-navigation] Apply theme context to popupmenu and drawermenu

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/drawer-menu/DrawerMenuUser.module.scss
Add z-index to drawer avatar to address embedded browser issue.
Standard test pass to ensure passivity. Validated against custom hardware setup manually.
@cerner/terra
> [terra-application-navigation] Add z-index to drawer avatar

- packages/terra-application-name/CHANGELOG.md
- packages/terra-application-name/tests/wdio/application-header-name-spec.js
This PR changes `waitForDisplayed` to `waitForExist` in wdio tests as [this](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-name/src/ApplicationHeaderName.module.scss#L26) property in themes is set to `none`. Because of this tests are failing in themes.
@cerner/terra
> [terra-application-name] Update wdio tests to fix failing tests in themes

- CONTRIBUTORS.md
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/src/terra-dev-site/doc/notification-dialog/UpgradeGuide.2.doc.mdx
The upgrade guide states to use `acceptAction` instead of both `primaryAction` and `secondaryAction`. `secondaryAction` can be seen to map to `rejectAction` [here](https://github.com/cerner/terra-framework/commit/6cd257b69caaffc815be1569edde8e242cbb71d1#diff-74e15fa34d531e4063a7d35c6bf8ff86087bb1647208d939fc45db811a3748bdL279) (expand `NotificationDialog.jsx` and it will jump to the linked line).
I've also updated my github username in the contributors file.
@cerner/terra
> [terra-notification-dialog] Correct upgrade guide

- package.json
This PR makes it easy to start our jest task in a debuggable mode. Once `jest:debug` is run, you can [attach a debugger of your choice (e.g. Chrome, VS Code ...)](https://nodejs.org/en/docs/guides/debugging-getting-started/).
**How to use**
Step 1: Run the `jest:debug` task
Step 2: Attach your debugger (e.g. in VS Code)
Step 3: Start the debugger! (e.g. in VS Code)
> Easy jest debugging

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
I saw this error when running a fresh `npm install`:
```
lerna WARN EHOIST_ROOT_VERSION The repository root depends on terra-application@^1.48.0, which differs from the more common terra-application@^1.12.0.
lerna WARN EHOIST_PKG_VERSION "terra-application-navigation" package depends on terra-application@^1.12.0, which differs from the hoisted terra-application@^1.48.0.
```
This change fixes that error.
TBD
No new tests. It's a minor version dependency change so I'm not too worried. Let's see how the CI does.
> Resolved dependency error

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/src/DateInput.jsx
Swaps to using `event.key` to detect keyboard shortcuts instead of `event.keyCode` since KeyCodes can differ between browsers. 
Closes #
@cerner/terra
> [terra-date-input] Keyboard shortcut detection fix for firefox

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/jest/header/__snapshots__/CompactHeader.test.jsx.snap
- packages/terra-application-navigation/tests/jest/header/__snapshots__/Header.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenuHeaderButton.test.jsx.snap
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/Tabs.1.doc.mdx
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/TabPane.jsx
- packages/terra-tabs/tests/jest/__snapshots__/TabPane.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/Tabs.test.jsx.snap
- scripts/release/gitTagMonoRepo.js
```jsx
const attributes = { ...customProps };
<div {...attributes} role="tab" className={paneClassNames}>
```
since `showIcon` was not extracted as props it got added as customProps (attributes) to [tabPane's div](https://github.com/cerner/terra-framework/blob/2b54fee079a7c76c9aae9ea7ea219f9893412cb5/packages/terra-tabs/src/TabPane.jsx#L84) causing below warnings on console.
``js
Warning: React does not recognize the `showIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.  
``
Consuming project has below config which will make jest to fail for console warnings / errors.
```js
console.error = (message, props) => …
```
> [Terra-Tabs] Fixed console warnings and travis build issue.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/jest/common/__snapshots__/PopupMenu.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/tests/jest/__snapshots__/UtilityMenuItem.test.jsx.snap
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/tests/jest/__snapshots__/CollapsibleMenuViewItem.test.jsx.snap
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/tests/jest/__snapshots__/TimeClarification.test.jsx.snap
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/tests/jest/__snapshots__/DialogModal.test.jsx.snap
- packages/terra-dialog-modal/tests/wdio/dialog-modal-spec.js
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/tests/jest/__snapshots__/NavigationSideMenu.test.jsx.snap
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/tests/jest/__snapshots__/NotificationDialog.test.jsx.snap
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/tests/jest/__snapshots__/PopupContent.test.jsx.snap
PR updates Jest failures happening due to release of terra-button. A11y features added to button has introduced new prop `iconType` for button which has been updated in all consuming component jest snapshots to fix test failures.
Closes #
@cerner/terra
> Updates Jest Snapshots for terra-button A11y changes

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose-wdio.yml
- .devcontainer/docker-compose.yml
- README.md
- package.json
Adds ability to run npm commands locally on a Docker container using VScode devcontainers setup
[MPAGESCORE-88019](https://jira2.cerner.com/browse/MPAGESCORE-88019)
@cerner/terra
> Add ability to use Docker Dev Container locally

- dangerfile.js
This PR updates `dangerfile.js` to ignore changes to files outside of `package.json`, `src`, `translations` and `terra-framework-docs`.
The changes to the logic were tested in https://github.com/cerner/terra-core/pull/3763.
@cerner/terra
> Update Dangerfile to ignore non-shipped folders

- .github/workflows/ci-cd.yml
Fixing bug where PR previews are deleted when main gh-pages branch is published.
Closes #
N/A 
Tested by fixing in terra-core.
@cerner/terra
> updating ghpages to keep existing files

- CONTRIBUTORS.md
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/slide-panel/SlidePanelToggledOnFullscreen.test.jsx
- packages/terra-slide-panel-manager/tests/jest/__snapshots__/SlidePanelManager.test.jsx.snap
- packages/terra-slide-panel/CHANGELOG.md
- packages/terra-slide-panel/src/SlidePanel.jsx
- packages/terra-slide-panel/src/SlidePanel.module.scss
- packages/terra-slide-panel/tests/jest/SlidePanel.test.jsx
- packages/terra-slide-panel/tests/jest/__snapshots__/SlidePanel.test.jsx.snap
- packages/terra-slide-panel/tests/wdio/slide-panel-spec.js
Changes how SlidePanel handles tab order when the panel content is open and fullscreen. Prevents main content (under panel content) from being focused when panel content is fullscreen either via `isFullscreen` prop or a narrow viewport size.
Tested manually in Chrome/Firefox/Safari on MacOS, and in Edge on Windows 10.
Preview: https://engineering.cerner.com/terra-framework/pull/1638
@cerner/terra
> [terra-slide-panel] Contain focus in panel content when fullscreen

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/_ModalContent.jsx
- packages/terra-abstract-modal/src/inertHelpers.js
- packages/terra-abstract-modal/tests/jest/__snapshots__/AbstractModal.test.jsx.snap
- packages/terra-abstract-modal/tests/jest/inertHelpers.test.jsx
- packages/terra-abstract-modal/tests/wdio/abstract-modal-spec.js
- packages/terra-dialog-modal/tests/wdio/dialog-modal-spec.js
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/src/ModalManager.jsx
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
- packages/terra-modal-manager/tests/wdio/modal-manager-spec.js
- packages/terra-notification-dialog/tests/jest/__snapshots__/NotificationDialog.test.jsx.snap
When entering a modal, the h1 title of the modal should be read by the screen reader. 
The required behavior was achieved by introducing an additional non-hidden empty span with tabIndex=-1, data-terra-abstract-modal-begin attribute and assign focus on dialog opening.
UXPLATFORM-8733
---
@cerner/terra
> [terra-modal-manager] Changed modal name to be the same as h1 title of the modal dialog

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/AbstractModal.jsx
- packages/terra-abstract-modal/src/_ModalContent.jsx
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/src/ModalManager.jsx
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
When entering a modal and its nested disclosures, the h1 title of the modal should be read by the screen reader.
The required behavior was achieved by introducing an additional non-hidden empty span with tabIndex=-1, data-terra-abstract-modal-begin attribute and assign focus on dialog opening. Additionally, reference to the span was passed to read the heading for nested disclosures.
UXPLATFORM-8733
@cerner/terra
> Added screen reader support for nested modalManager disclosures

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/worklist-data-grid/example/gridData.json
- packages/terra-framework-docs/src/terra-dev-site/test/worklist-data-grid/gridData.json
- packages/terra-worklist-data-grid/CHANGELOG.md
- packages/terra-worklist-data-grid/src/WorklistDataGrid.jsx
- packages/terra-worklist-data-grid/src/proptypes/rowShape.js
The ability to specify a height for each specific row was removed.
Based on the updated requirements, all rows of the worklist data grid should be the same height.
N/A
UXPLATFORM-9044
---
@cerner/terra
> [terra-worklist-data-grid] Remove ability to vary the row height

- CONTRIBUTORS.md
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventsConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/DataStatusConsumer.jsx
Updated the path name of the dependency file which uses in the examples in terra-embedded-content-consumer
The update is needed to resolve the 404 missing file
UXPLATFORM-9302
---
@cerner/terra
> [terra-embedded-content-consumer] Updated the path name for the examples in doc site to resolve missing files

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
This PR backpatches terra-tabs@6 by downgrading UUID to v3 for compatibility reasons.
---
@cerner/terra
> [terra-tabs] Downgrade UUID to v3

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/worklist-data-grid/Examples.2/RowSelection.jsx
- packages/terra-worklist-data-grid/CHANGELOG.md
- packages/terra-worklist-data-grid/src/WorklistDataGrid.jsx
- packages/terra-worklist-data-grid/src/utils/WorklistDataGridUtils.js
- packages/terra-worklist-data-grid/tests/jest/WorklistDataGrid.test.jsx
- packages/terra-worklist-data-grid/tests/jest/__snapshots__/WorklistDataGrid.test.jsx.snap
The WorklistDataGrid was updated to make the row selection column header selectable so that consumers can be notified when it is selected.
The MPages Worklist Framework needs the ability to sort the row selection column based on the selection state.  In order to facilitate this requirement, the WorklistDataGrid component needs the ability to notify consumers when the row selection column header is selected.
The row selection example for the WorklistDataGrid was updated to facilitate testing of the row selection column header.
N/A
UXPLATFORM-9460 
---
@cerner/terra
> [terra-worklist-data-grid] Make Row Selection Column Header Selectable

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/worklist-data-grid/PinnedColumns.test.jsx
- packages/terra-worklist-data-grid/CHANGELOG.md
- packages/terra-worklist-data-grid/package.json
- packages/terra-worklist-data-grid/src/WorklistDataGrid.jsx
- packages/terra-worklist-data-grid/tests/jest/__snapshots__/WorklistDataGrid.test.jsx.snap
Modified WorklistDataGrid logic such that the border height for the pinned column separator adjust to table height changes.
The change was made to ensure the separator is visible and looks correct to users.
N/A
UXPLATFORM-9526 
---
@cerner/terra
> [terra-worklist-data-grid] Fix height of pinned column border

- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItem.jsx
- packages/terra-collapsible-menu-view/tests/jest/CollapsibleMenuViewItem.test.jsx
- packages/terra-collapsible-menu-view/tests/jest/__snapshots__/CollapsibleMenuViewItem.test.jsx.snap
Currently, the main collapsible menu button and regular menu buttons with submenu items do not announce to screen readers that interacting with them will open a dialog popup with additional controls. This creates a poor experience for screen reader users since there is nothing distinguishing menu buttons that will open a collapsible menu from regular buttons.
Added the `aria-haspopup` attribute to menu buttons.
So screen reader users are provided the context that menu buttons will open a dialog popup.
https://github.com/cerner/terra-framework/assets/37230460/42779662-1317-4f03-b5d9-6885def5ffd8
https://github.com/cerner/terra-framework/assets/37230460/8acd4b05-112c-45a4-a2ca-ab37ad19c158
In addition to engineering …
> [terra-collapsible-menu-view] Add aria-haspopup attribute to menu buttons

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/common-tabs/TerraStructuralTabs.module.scss
removed additional focus border.
"blue border" is completely removed as we already have a dotted focus indicator and an active tab indicator as well (bottom blue border)
UXPLATFORM-9370 
**Pre Implementation :**
**Post Implementation :**
---
@cerner/terra
> [terra-tabs] Removed browser specific focus border appearing when using both mouse and keyboard subsequently.

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DateInput.jsx
- packages/terra-date-picker/src/DatePicker.jsx
- packages/terra-date-picker/src/DateUtil.js
- packages/terra-date-picker/tests/jest/DatePicker.test.jsx
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
- packages/terra-date-picker/tests/wdio/date-picker-spec.js
- packages/terra-date-picker/translations/de.json
- packages/terra-date-picker/translations/en-AU.json
- packages/terra-date-picker/translations/en-CA.json
- packages/terra-date-picker/translations/en-GB.json
- packages/terra-date-picker/translations/en-US.json
- packages/terra-date-picker/translations/en.json
- packages/terra-date-picker/translations/es-ES.json
- packages/terra-date-picker/translations/es-US.json
- packages/terra-date-picker/translations/es.json
- packages/terra-date-picker/translations/fr-FR.json
- packages/terra-date-picker/translations/fr.json
- packages/terra-date-picker/translations/nl-BE.json
- packages/terra-date-picker/translations/nl.json
- packages/terra-date-picker/translations/pt-BR.json
- packages/terra-date-picker/translations/pt.json
- packages/terra-date-picker/translations/sv-SE.json
- packages/terra-date-picker/translations/sv.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/date-picker/example/DatePickerField.jsx
- Updated screen reader response to announce when invalid dates are entered.
- Updated screen reader response to announce when calendar popup dates are selected.
- Updated example for invalid date entry.
- Screen reader currently does not provide context when non-number inputs OR invalid dates are entered in Date Picker fields.
- Screen reader fails to announce the selected date under calendar popup. 
UXPLATFORM-9479 
---
@cerner/terra
> [terra-date-picker] Screen reader updates for invalid dates and calendar date selection

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/example/AddCloseTab.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/example/AddCloseTabInteractive.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/example/AddTab.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/tabs/Tabs/AddCloseInteractiveTab.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/tabs/Tabs/AddCloseTab.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/tabs/Tabs/AddNewTabs.test.jsx
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/Tabs.jsx
If an active tab key is present in the tab data, the active key variable is set to prop active key else state the active key.
On Selecting the tab, the Dotted Focus is added but the underlined active key tab indicator is missing.
UXPLATFORM-9640 
---
@cerner/terra
> Fix for Active Key Indicator.

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/common-tabs/_HiddenTab.jsx
- packages/terra-tabs/src/common-tabs/_Tab.jsx
- packages/terra-tabs/tests/jest/__snapshots__/Tab.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/TabPane.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/Tabs.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/_HiddenTab.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/_TabDropDown.test.jsx.snap
- Fixed Axe core violations for close button added on terra-tabs on both face-up tab and hidden tab.
- Fixed issue in screen reader instruction for hidden tabs where add tab instruction is announced even in absence of add button.
- Screen reader instructions are inappropriate for hidden tabs. when we navigate to hidden tabs screen reader announce press space or enter to add new tab even when there is no add button available on menu ( as shown in the screenshot of VO). We need to add the instruction only of onAddSelect callback is provided.
- Axe core violations for close button added on terra-tabs on both face-up tab and hidden tab.
`Ensures ARIA attributes are allowed for an element's role` 
`Ensures interactive controls are not nested as …
> [terra-tabs] Fixes axe core violations, SR response for hidden tabs

- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
- packages/terra-dialog-modal/tests/jest/__snapshots__/DialogModal.test.jsx.snap
- packages/terra-navigation-side-menu/tests/jest/__snapshots__/NavigationSideMenu.test.jsx.snap
- packages/terra-notification-dialog/tests/jest/__snapshots__/NotificationDialog.test.jsx.snap
- packages/terra-popup/tests/jest/__snapshots__/PopupContent.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/Tabs.test.jsx.snap
- packages/terra-tabs/tests/jest/__snapshots__/_AddButton.test.jsx.snap
- packages/terra-time-input/tests/jest/__snapshots__/TimeInput.test.jsx.snap
This PR updates failing Jest snapshots (due to the changes from https://github.com/cerner/terra-core/pull/3920) so that the build is passing.
---
@cerner/terra
> Update Jest snapshots to fix the build

- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/src/Popup.jsx
Defect is when "click" event on pop-up does not bleed through to other components / controls.
If we render a popup in a table, if the user clicks on that popup, a table row will still receive the click.
The popup needs to "absorb" the click event and not allow it to "bubble" up or "bleed through" to other controls.
UXPLATFORM-9651  
Pre Implementation->
https://github.com/cerner/terra-framework/assets/126875089/e1150961-bc4f-466a-a411-bd5a47c9962c
Post Implementation->
https://github.com/cerner/terra-framework/assets/126875089/e3a36674-ced5-499b-801e-a78e80317906
---
@cerner/terra
> [terra-popup] Popup with table example fix

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/common-tabs/_Tab.jsx
Fixes response when tabs are closed.
Deleted/Closed tab was announced as "tab_name removed, selected....." 
UXPLATFORM-9765 
Updated response (Same with JAWS and VO)
---
@cerner/terra
> [terra-tabs] Fixes screen reader response when tabs are closed.

- package-lock.json
This PR updates package-lock so that it is up to date with main.
Note: The build is failing due to an a sub dependency update (https://github.com/cerner/terra-framework/actions/runs/6659718947/job/18099412922?pr=1857). While we haven't been able to identify the dependency yet, we were able to to get it to work with this package-lock.json. 
The change was tested by running `npm start` to make sure that the project compiles and starts correctly.
---
@cerner/terra
> Updated package-lock with main.

- packages/terra-menu/tests/jest/__snapshots__/Menu.test.jsx.snap
Fix a snapshot test post NPM CI with package lock.
To be consistent after the adoption of NPM CI w/ package-lock.json, and to fix a 3rd party dependency issue.
---
@cerner/terra
> Fix Snapshot in NPM CI

- package-lock.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItemGroup.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/AlwaysCollapsedMenuItemsDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewStartAligned.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewWithMultiSelectItems.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/menu/example/BasicMenu.jsx
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/MenuItem.jsx
- packages/terra-menu/src/_MenuContent.jsx
- packages/terra-menu/tests/jest/__snapshots__/Menu.test.jsx.snap
Screen Reader not fetching group name information because we are wrapping group role items within menu role
If additional group information text is used, provide a string containing the IDs for html elements that help describe the intent of the group of menu. so added `aria-describedby` attribute in menu items and passing group id to aria-describedby 
Screen Reader not fetching group name information
UXPLATFORM-9744 
---
@cerner/terra
https://github.com/cerner/terra-framework/assets/127083404/46c15e3f-f449-456b-aaeb-0f35ec7b8a91
https://github.com/cerner/terra-framework/assets/127083404/981fea85-6551-41c6-9 …
> [terra-menu] - Fixed SR not announcing menu group name information.

- packages/terra-data-grid/translations/de.json
- packages/terra-data-grid/translations/en-GB.json
- packages/terra-data-grid/translations/en-US.json
- packages/terra-data-grid/translations/en.json
- packages/terra-data-grid/translations/es.json
- packages/terra-data-grid/translations/fr.json
- packages/terra-data-grid/translations/nl.json
- packages/terra-data-grid/translations/pt.json
- packages/terra-data-grid/translations/sv.json
- packages/terra-table/translations/de.json
- packages/terra-table/translations/en-GB.json
- packages/terra-table/translations/es.json
- packages/terra-table/translations/fr.json
- packages/terra-table/translations/nl.json
- packages/terra-table/translations/pt.json
- packages/terra-table/translations/sv.json
Obsolete translations from the data-grid package are moved to Table Package.
To add in necessary translations for the Table package.
UXPLATFORM-9543 
---
@cerner/terra
> [terra-data-grid] [terra-table] Move translations from DataGrid to Table Package

- package-lock.json
- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-slider/CHANGELOG.md
- packages/terra-slider/package.json
- packages/terra-table/CHANGELOG.md
- packages/terra-table/package.json
- terra-data-grid@1.2.0
- @cerner/terra-framework-docs@1.45.0
- terra-slider@1.1.1
- terra-table@5.1.1-alpha.2
---
@cerner/terra
> Release for Nov 20, 2023

- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/utils/constants.js
- packages/terra-data-grid/tests/jest/DataGrid.test.jsx
- packages/terra-table/CHANGELOG.md
- packages/terra-table/src/Table.jsx
- packages/terra-table/src/utils/constants.js
- packages/terra-table/tests/jest/Table.test.jsx
The console messages that triggered when no pinned columns were defined were removed.
Several use cases were identified where pinned columns were not required.  The console warnings were confusing consumers and making code maintenance difficult.  The warnings introduce error fatigue and errors were being missed in the development process.
N/A
UXPLATFORM-9904 
---
@cerner/terra
> [terra-table] Remove Console Warning Message when No Pinned Columns

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/table/About.1.doc.mdx
- packages/terra-table/CHANGELOG.md
- packages/terra-table/src/Table.jsx
- packages/terra-table/src/index.js
The row selection column width was exported for the Terra Table.
Consumers needed to adjust their container by the width of the column when the column was made visible.  The constant provides a means to supply this value to consumers.
N/A
UXPLATFORM-9913 
---
@cerner/terra
> [terra-table] Export Row Selection Column Width

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumerWithScrolling.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventsConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/DataStatusConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/BasicProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/BasicProviderWithScrolling.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/CustomEventProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/CustomEventsProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/DataStatusProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithNoScrolling.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithScrolling.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/CustomEventConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/CustomEventsConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/DataStatusConsumer.test.jsx
Update prefix for examples, tests, and remove redundant XFC Provider initialization for terra-embedded-content-consumer
Update prefix for examples, tests, and remove redundant XFC Provider initialization for terra-embedded-content-consumer
- In order to correct file not found when viewing the examples and tests in terra-embedded-content-consumer
- Remove redundant XFC Provider initialization in the providers
UXPLATFORM-9772  
---
@cerner/terra
> [terra-framework-docs] Update prefix for examples, tests, and remove redundant XFC Provider initialization for terra-embedded-content-consumer

- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/About.1.doc.mdx
This PR:
1. Removes the "compact interactive list is under alpha release" banner. 
2. Adds a CHANGELOG entry for the previously made changes to the `terra-framework-docs`.
3. Corrects a typo in the CHANGELOG in `terra-compact-list`.
> removed the banner

- package-lock.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/package.json
- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/package.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
- terra-compact-interactive-list@1.0.0
- terra-data-grid@1.10.0
- terra-date-input@1.48.0
- terra-date-time-picker@4.102.0
- terra-form-validation@1.93.0
- @cerner/terra-framework-docs@1.54.0
- terra-time-input@4.60.0
> Release for January 2nd, 2024

- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/src/CompactInteractiveList.jsx
- packages/terra-compact-interactive-list/src/proptypes/validators.js
- packages/terra-compact-interactive-list/src/utils/constants.js
This PR adds `rowHeaderIndex` prop validation similarly to how it is done in `terra-table` component here:
https://github.com/cerner/terra-framework/blob/main/packages/terra-table/src/proptypes/validators.js
https://github.com/cerner/terra-framework/blob/main/packages/terra-table/src/utils/constants.js
Testing steps:
1. In `terra-framework-docs` I went to a `compact-interactive-list` example and changed the `rowHeaderIndex` prop to the integer value that exceeded the number of semantic columns in a row. In developer tool consol I observed the error stating that *Prop rowHeaderIndex exceeds the number of semantic columns in the row*:
2. I changed the `rowHeaderIndex` prop value to -1 and observed the error stating that *Prop rowHeaderIndex must be a positive …
> rowHeaderIndex prop validation added

- packages/terra-pills/CHANGELOG.md
- packages/terra-pills/src/subcomponents/Pill.module.scss
terra-pills uses `@supports selector(:-moz-is-html)` to apply firefox specific styles of pill label. `selector` rule is not supported on older version of mini-css-extract-plugin due to this applications which are dependent on packages like terra-toolkit, webpack-config-terra, mini-css-extract-plugin < 3 has error `**_SassError: Invalid CSS after "    @supports ": expected @supports condition (e.g. (display: flexbox)), was "selector(:-moz-is-h"_**` 
Unsupported browser specific rule `@supports selector(:-moz-is-html)` is replaced with supported rule `@-moz-document url-prefix()` 
Since most of clinical applications are not planning to have tech upgrade sooner, unsupported css rule `@supports selector(:-moz-is-html)` is blocking applications …
> [Terra-Pills] Resolves Sass Error caused due to usage of @supports selector rule

- packages/terra-theme-properties/CHANGELOG.md
- packages/terra-theme-properties/src/scss/redwood-mixins.scss
A mixin was created so that consumers could properly render the focus ring for the Redwood theme.
The mixin was created to ensure proper implementation and consistency.
UXPLATFORM-10151 
---
@cerner/terra
> [terra-theme-properties] Redwood focus indicator mixin

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DateInput.jsx
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
Update Screen reader response not to read visually hidden text with name attribute.
When user first navigates to the date input field, then the visually hidden text with name attribute is exposed to user which is not contextual and can be confusing.
https://github.com/cerner/terra-framework/assets/132886427/42cc15c4-bea6-4a67-a66d-5e3f659ab4fd
UXPLATFORM-10137 
---
@cerner/terra
> [date-time-picker] Update Screen reader response not to read visually hidden text with name attribute.

- package-lock.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
The following components are released -
- terra-date-input@1.50.0
- terra-date-picker@4.97.0
- terra-date-time-picker@4.104.0
- terra-dialog-modal@3.100.0
- terra-form-validation@1.96.0
- @cerner/terra-framework-docs@1.60.0
- terra-time-input@4.61.0
---
@cerner/terra
> Release 25/01

- package-lock.json
- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/DataGrid.jsx
- packages/terra-data-grid/src/FlowsheetDataGrid.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/data-grid/flowsheet-data-grid/BoundedFlowsheetWithSections.test.jsx
- packages/terra-table/CHANGELOG.md
- packages/terra-table/src/Table.jsx
- packages/terra-table/src/subcomponents/Section.jsx
Changed flowsheet sections to have sticky titles.
When flowsheet with sections are height restricted and have more cells in row, the section header is still absolute in its position. Due to this title of `terra-section-header` is made sticky during horizontal scroll.
https://github.com/cerner/terra-core/pull/4037 
https://github.com/cerner/terra-core/pull/4043
UXPLATFORM-10215 
---
@cerner/terra
> [terra-flowsheet-data-grid] Allow flowsheet sections to have sticky title

- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/src/CompactInteractiveList.jsx
This PR adds a check if row and cell element exist before focusing on the last one. That allows to avoid errors in cases the cell implementation is different from documented.
MPAGESCORE-91600
> check if element exists before focusing added

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/react-datepicker/calendar.jsx
Currently when navigating through the Date Picker popup and selecting a value for "Month"/ "Year", will only expose the selected value. But, the selected value is getting exposed twice as "February, Month Combobox February", .
---
@cerner/terra
> [Date-Time-Picker] Month/Year changing redundant announcement fix

- packages/terra-table/src/subcomponents/Cell.jsx
This PR reorganizes the cell.jsx file for easier maintenance & readability by moving the code into labelled sections. There are no functional changes in this PR.
---
@cerner/terra
> [terra-table] Rerganized Cell.jsx for easier maintenance & readability 

- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/DataGrid.jsx
Fixes page crash issue of worklist data grid in row selection mode. 
column index range exceeds the displayed column length in row selection mode when toggled on/off in last column of grid.
UXPLATFORM-10242 
---
@cerner/terra
> [terra-worklist-data-grid] Fixes column index out of range for displayed columns

- packages/terra-time-input/tests/wdio/time-input-spec.js
Currently, if the time input has no time entered, per "+" key press it fills the time with current time +1 second. If "-" pressed -1 second. 
The wdio tests for that functionality are checking if the input time is in 2 seconds range from expected value, using real time instead of mocked value, which caused tests failure in 80% of cases.
This PR is temporary fix to prevent delays caused by tests failures. It replaces check for seconds be in proper time range to check for seconds to have a value in between 0 and 59. The tests needs to be updated with proper check for seconds being +1/-1 compared to current time, where current time is properly mocked. That work should be done as a part of UXPLATFORM-10295.
This …
> time input tests fix

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/common-tabs/TabDropDown.module.scss
- packages/terra-tabs/src/common-tabs/_TabDropDown.jsx
Added max height to the dropdown container and reset the left position value to 0 when dropdown is closed.
More Button is Not Accessible using Keyboard or Mouse / Additional White Space Added in Revenue cycle application
---
@cerner/terra
> [terra-tabs]: More Button is Not Accessible using Keyboard or Mouse / Additional White Space Added

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/BasicCompactInteractiveList.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/FixedWidthColumns.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/HorizontalFlow.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/ResponsiveColumns.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/ResponsiveColumnsMaxWidth.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/ScalableUnits.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/VerticalFlow.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/compact-interactive-list/Examples.2/WidthBreakpoints.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/Borderless.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/FixedWidthColumns.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/InconsistentWidthUnits.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/ResponsiveColumns.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/ResponsiveColumnsMaxWidth.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/ScalableUnits.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/WidthBreakpoints.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/compact-interactive-list/WidthBreakpointsHorizontalFlow.test.jsx
Updated `terra-compact-interactive-list` examples to remove the word "button" from terra-button text, which was leading to the word "button" to be announced twice. 
Previously Featured buttons (represented by star icon in examples), had text that would read "Featured button". That text would be announced by assistive technologies, followed by the second "button" word, to indicate that it was a button element. The text was replaced to read "Favorite Item", hence the full announcement changed to be "Favorite Item Button".
To test with JAWS, in Compact Interactive List examples tab to the compact interactive list, then using arrow keys navigate to the star icon:
The announcement should be "Favorite Item Button", not "Featured Button Button".
In addition to …
> [compact-interactive-list] Examples updated to remove redundant button announcement.

- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/src/CompactInteractiveList.jsx
Fix to put focus on first item only on initial render by adding empty dependency array in useEffect.
MPages custom lifecycle method is triggering the react lifecycle method unexpectedly hence a workaround is added.
UXPLATFORM-10272 
---
@cerner/terra
> [terra-compact-interactive list] Fix to put focus on first item only on initial render

- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/translations/sv-SE.json
- packages/terra-notification-dialog/translations/sv.json
This PR replaces **terra-notification-dialog** headers Swedish translations for locales **sv** and **sv-SE** to match the new translations used elsewhere.
UXPLATFORM-10362
> Headers Swedish old translations fixed

- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItem.jsx
- packages/terra-collapsible-menu-view/tests/jest/CollapsibleMenuViewItem.test.jsx
- packages/terra-collapsible-menu-view/tests/jest/__snapshots__/CollapsibleMenuViewItem.test.jsx.snap
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/Menu.jsx
- packages/terra-menu/src/_MenuContent.jsx
- packages/terra-menu/tests/jest/__snapshots__/Menu.test.jsx.snap
- Sets aria-haspopup to boolean values
- Removed dialog role terra-menu
- aria-haspopup was set to dialog, changed to boolean.
- Dialog role causes axe a11y failure being an inappropriate role.
UXPLATFORM-10322 
---
@cerner/terra
> [terra-collapsible-menu-view] Removes dialog role for menu and sets aria-haspopup

- packages/terra-pills/CHANGELOG.md
- packages/terra-pills/src/FilterPills.jsx
Replaced direct invocation of `handleResize` inside `ResizeObserver` callback with a debounced function.
To prevent potential cyclic dependencies leading to infinite loops, ensuring that handleResize is called only after a specified delay, thus resolving the issue.
UXPLATFORM-10369 
---
@cerner/terra
> [terra-pills] Added debouncing for resize observer

- packages/terra-folder-tree/CHANGELOG.md
- packages/terra-folder-tree/src/FolderTree.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/folder-tree/Examples.2/BasicFolderTree.module.scss
Updated aria-control label.
Removed default width for the folder tree example
In 400% browser zoom, some of the folders are hiding from the screen. Therefor user don't have access to some folders and they can't be accessed.
Axe issues - Invalid ARIA attribute value: aria-controls="Folder" in the toolbar 'expand all and collapse all' section
UXPLATFORM-10399- 
---
@cerner/terra
> [terra-folder-tree] Fix axe invalid aria attribute and 400% browser zoom

- packages/terra-application-layout/tests/jest/__snapshots__/ApplicationLayout.test.jsx.snap
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/modal-manager/example/ModalManagerExample.jsx
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/src/ModalManager.jsx
- packages/terra-modal-manager/tests/jest/ModalManager.test.jsx
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
Added `zIndex` prop to allow consumers to set custom z-index to modals.
Custom zindex will allow consumers to have nested modals.
UXPLATFORM-10380 
---
@cerner/terra
> [terra-modal-manager] Added zIndex prop to handle nested modals.

- packages/terra-folder-tree/src/subcomponents/FolderTreeItem.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/outline-view/example/DefaultOutlineView.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/outline-view/DefaultOutlineView.test.jsx
- packages/terra-navigation-side-menu/package.json
- packages/terra-navigation-side-menu/src/MenuItem.module.scss
- packages/terra-navigation-side-menu/src/NavigationSideMenu.jsx
- packages/terra-navigation-side-menu/src/_MenuItem.jsx
- packages/terra-outline-view/src/OutlineView.jsx
- packages/terra-outline-view/src/subcomponents/OutlineViewItem.jsx
- Added icon for terra-navigation-side-menu items (as part of Outline-View:Drill-In display)
- Outline-View:Drill-In design requires icon of type Documents/Folder/Location for list items.
UXPLATFORM-10382 
---
@cerner/terra
> [terra-outline-view] Add icon for nav-side-menu

- package-lock.json
- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/_ModalContent.jsx
- packages/terra-abstract-modal/tests/jest/__snapshots__/AbstractModal.test.jsx.snap
- packages/terra-abstract-modal/translations/de.json
- packages/terra-abstract-modal/translations/en-AU.json
- packages/terra-abstract-modal/translations/en-CA.json
- packages/terra-abstract-modal/translations/en-GB.json
- packages/terra-abstract-modal/translations/en-US.json
- packages/terra-abstract-modal/translations/en.json
- packages/terra-abstract-modal/translations/es-ES.json
- packages/terra-abstract-modal/translations/es-US.json
- packages/terra-abstract-modal/translations/es.json
- packages/terra-abstract-modal/translations/fi-FI.json
- packages/terra-abstract-modal/translations/fr-FR.json
- packages/terra-abstract-modal/translations/fr.json
- packages/terra-abstract-modal/translations/nl-BE.json
- packages/terra-abstract-modal/translations/nl.json
- packages/terra-abstract-modal/translations/pt-BR.json
- packages/terra-abstract-modal/translations/pt.json
- packages/terra-abstract-modal/translations/sv-SE.json
- packages/terra-abstract-modal/translations/sv.json
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
- packages/terra-modal-manager/src/ModalManager.jsx
- packages/terra-modal-manager/src/index.js
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/src/Popup.jsx
Changed 'begin modal dialog` to include modal title passed as aria label.
To allow screen reader to announce title in. powerchart
UXPLATFORM-10411 
---
@cerner/terra
> [terra-abstract-modal] Customise Modal span text
