cerner/terra-framework

- README.md
- packages/terra-framework-site/package.json
- packages/terra-framework-site/src/componentConfig.js
- packages/terra-framework-site/src/examples/theme-provider/DefaultThemeProvider.jsx
- packages/terra-framework-site/src/examples/theme-provider/Index.jsx
- packages/terra-framework-site/src/examples/theme-provider/MockThemeComponent.jsx
- packages/terra-framework-site/src/examples/theme-provider/MockThemeComponent.scss
- packages/terra-framework-site/themeable-variables.json
- packages/terra-theme-provider/.npmignore
- packages/terra-theme-provider/.npmrc
- packages/terra-theme-provider/CHANGELOG.md
- packages/terra-theme-provider/LICENSE
- packages/terra-theme-provider/NOTICE
- packages/terra-theme-provider/README.md
- packages/terra-theme-provider/docs/DEPENDENCIES.md
- packages/terra-theme-provider/docs/README.md
- packages/terra-theme-provider/package.json
- packages/terra-theme-provider/src/ThemeProvider.jsx
- packages/terra-theme-provider/tests/jest/ThemeProvider.test.jsx
- packages/terra-theme-provider/tests/jest/__snapshots__/ThemeProvider.test.jsx.snap
- packages/terra-theme-provider/tests/nightwatch/DefaultThemeProvider.jsx
- packages/terra-theme-provider/tests/nightwatch/GlobalSwitchThemes.jsx
- packages/terra-theme-provider/tests/nightwatch/GlobalThemeProvider.jsx
- packages/terra-theme-provider/tests/nightwatch/MockThemeComponent.jsx
- packages/terra-theme-provider/tests/nightwatch/MockThemeComponent.scss
- packages/terra-theme-provider/tests/nightwatch/SwitchThemes.jsx
- packages/terra-theme-provider/tests/nightwatch/ThemeProviderNoTheme.jsx
- packages/terra-theme-provider/tests/nightwatch/theme-provider-spec.js
Migrating [terra-theme-provider](https://github.com/cerner/terra-core/tree/master/packages/terra-theme-provider) component from terra-core.
https://terra-framework-deployed-pr-38.herokuapp.com/static/#/components/theme-provider
@cerner/terra
> Migrate theme-provider component

- lerna.json
- packages/terra-application-name/.npmignore
- packages/terra-application-name/.npmrc
- packages/terra-application-name/CHANGELOG.md
- packages/terra-application-name/LICENSE
- packages/terra-application-name/NOTICE
- packages/terra-application-name/README.md
- packages/terra-application-name/docs/README.md
- packages/terra-application-name/package.json
- packages/terra-application-name/src/ApplicationName.jsx
- packages/terra-application-name/src/ApplicationName.scss
- packages/terra-application-name/tests/jest/ApplicationName.test.jsx
- packages/terra-application-name/tests/jest/__snapshots__/ApplicationName.test.jsx.snap
- packages/terra-application-name/tests/nightwatch/ApplicationNameTestRoutes.jsx
- packages/terra-application-name/tests/nightwatch/ApplicationNameTests.jsx
- packages/terra-application-name/tests/nightwatch/DefaultApplicationName.jsx
- packages/terra-application-name/tests/nightwatch/application-name-spec.js
- packages/terra-framework-site/package.json
- packages/terra-framework-site/src/examples/application-name/Index.jsx
Generate a package to house #28. This ignores the new site changes that have not yet been merged.
@cerner/terra
> Initial terra-application-name package

- lerna.json
- packages/terra-application-utility/.npmignore
- packages/terra-application-utility/.npmrc
- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/LICENSE
- packages/terra-application-utility/NOTICE
- packages/terra-application-utility/README.md
- packages/terra-application-utility/docs/README.md
- packages/terra-application-utility/package.json
- packages/terra-application-utility/src/ApplicationUtility.jsx
- packages/terra-application-utility/src/ApplicationUtility.scss
- packages/terra-application-utility/tests/jest/ApplicationUtility.test.jsx
- packages/terra-application-utility/tests/jest/__snapshots__/ApplicationUtility.test.jsx.snap
- packages/terra-application-utility/tests/nightwatch/DefaultApplicationUtility.jsx
- packages/terra-application-utility/tests/nightwatch/application-utility-spec.js
- packages/terra-framework-site/package.json
- packages/terra-framework-site/src/examples/application-utility/Index.jsx
Initial package for application-utility. Will house #29 and #34.
@cerner/terra
> Generate application-utility package

- package.json
Attempting to fix the build
@cerner/terra
> Pin terra-site to 2.0.0-RC.3

- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/tests/jest/__snapshots__/Layout.test.jsx.snap
Reverts cerner/terra-framework#110
More info: https://github.com/adriantoine/enzyme-to-json/pull/91#issuecomment-371563680
> Revert "Update snapshots tests to match new default pattern updated by enzyme."

- .travis.yml
- package.json
- wdio.conf.js
Use the new express dev server service for wdio testing.
@cerner/terra
> Use the new express dev server service for wdio testing.

- packages/terra-popup/package.json
> Add terra-mixins dep

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/package.json
- packages/terra-slide-panel-manager/tests/jest/__snapshots__/SlidePanelManager.test.jsx.snap
This is still referencing react 15 dependencies.
@cerner/terra
> Update outdated slide panel manager dependencies.

- packages/terra-aggregator/.npmignore
- packages/terra-app-delegate/.npmignore
- packages/terra-application-header-layout/.npmignore
- packages/terra-application-layout/.npmignore
- packages/terra-application-links/.npmignore
- packages/terra-application-menu-layout/.npmignore
- packages/terra-application-name/.npmignore
- packages/terra-application-utility/.npmignore
- packages/terra-disclosure-manager/.npmignore
- packages/terra-hookshot/.npmignore
- packages/terra-infinite-list/.npmignore
- packages/terra-layout/.npmignore
- packages/terra-modal-manager/.npmignore
- packages/terra-navigation-layout/.npmignore
- packages/terra-navigation-side-menu/.npmignore
- packages/terra-popup/.npmignore
- packages/terra-slide-panel-manager/.npmignore
- packages/terra-slide-panel/.npmignore
- packages/terra-theme-provider/.npmignore
Update npm ignore files to ignore all snapshots
@cerner/terra
> Update npm ignore files to ignore all snapshots

- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/examples/test-examples/DefaultHeaderUtilityMenu.example.jsx
- packages/terra-application-utility/examples/test-examples/DefaultMenuUtilityMenu.example.jsx
Update test examples to account for inline-block icon changes.
@cerner/terra
> Correct failing tests by update test examples.

- package.json
- wdio.conf.js
This PR is preparing the project for a change that is going to happen in terra-toolkit to support parallelization.  This change will help prevent a major version bump in terra-toolkit.
> Prepare for toolkit

- .travis.yml
Try and improve the builds with caching.
> Try to improve builds

- .travis.yml
> Clean up cache on failures

- package.json
Resolves #157 and syncs with https://github.com/cerner/terra-core/pull/1433
> Update root stylelint check

- .travis.yml
- package.json
Enable new-relic monitoring for terra-framework and clean up travis-ci.yml
@cerner/terra
> Enable new-relic monitoring for terra-framework

- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/src/tabs/ApplicationTabs.jsx
- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/src/HookshotContent.jsx
Update life cycle of renders for application links.
Updated application links, and hookshot to use animation frames.
@cerner/terra
> Implement request animation frame to correct loop limit error.

- jestconfig.js
> Add jest config testURL to jsdom issue

- README.md
Add I18n Documentation to Readme
> Add I18n Documentation to Readme

- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
Update portal snapshot for use with enzyme v3.5.0
> Update portal snapshot

- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/src/terra-dev-site/doc/example/CoordsHookshotExample.jsx
Correct setState for coordinates example.
@cerner/terra
> Fix hookshot coordinate example.

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Update issue template to include mentions of terra members that have been worked with so far.
> Update issue template with mentions.

- CONTRIBUTORS.md
- package.json
- packages/terra-disclosure-manager/package.json
> Fix #295 (terra-base devDependency clean up)

- packages/terra-aggregator/docs/README.md
- packages/terra-application-header-layout/docs/README.md
- packages/terra-application-layout/docs/about.md
- packages/terra-application-links/docs/README.md
- packages/terra-application-menu-layout/docs/README.md
- packages/terra-application-name/docs/README.md
- packages/terra-application-utility/docs/README.md
- packages/terra-brand-footer/CHANGELOG.md
- packages/terra-brand-footer/docs/README.md
- packages/terra-dialog-modal/docs/README.md
- packages/terra-disclosure-manager/docs/README.md
- packages/terra-infinite-list/docs/README.md
- packages/terra-layout/docs/README.md
- packages/terra-modal-manager/README.md
- packages/terra-modal-manager/docs/README.md
- packages/terra-navigation-side-menu/README.md
- packages/terra-navigation-side-menu/docs/README.md
- packages/terra-notification-dialog/docs/README.md
- packages/terra-slide-panel-manager/docs/README.md
- packages/terra-slide-panel/docs/README.md
Updates component readmes to point to new feature links.
> Update component readmes

- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/src/NotificationDialog.module.scss
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/src/PopupContent.module.scss
- packages/terra-theme-provider/CHANGELOG.md
- packages/terra-theme-provider/src/terra-dev-site/theme/scoped-theme.scss
Resolves https://github.com/cerner/terra-core/issues/1997
> Update mixin to be compatible with codesandbox

- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/src/utility/_UtilityMenu.jsx
- packages/terra-application-utility/src/utility/_UtilityMenuItem.jsx
- packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx
- packages/terra-brand-footer/src/terra-dev-site/doc/example/DefaultBrandFooter.jsx
- packages/terra-brand-footer/src/terra-dev-site/test/brand-footer/DefaultBrandFooter.test.jsx
- packages/terra-brand-footer/src/terra-dev-site/test/brand-footer/LinksPropBrandFooter.test.jsx
- packages/terra-brand-footer/src/terra-dev-site/test/brand-footer/NoNavBrandFooter.test.jsx
- packages/terra-brand-footer/src/terra-dev-site/test/brand-footer/VerticalMixedHeadersBrandFooter.test.jsx
- packages/terra-disclosure-manager/src/DisclosureManager.jsx
- packages/terra-navigation-layout/tests/jest/NavigationLayout.test.jsx
- packages/terra-notification-dialog/src/terra-dev-site/test/notification-dialog/NotificationDialogVariant.test.jsx
- packages/terra-popup/src/_PopupOverlay.jsx
Fixes all but 1 lint error. I'm curious how to handle the remaining lint error.
> Fix lint errors related to eslint-react-plugin update

- packages/terra-aggregator/docs/README.md
- packages/terra-disclosure-manager/docs/README.md
- packages/terra-modal-manager/docs/UPGRADEGUIDE.md
- packages/terra-slide-panel-manager/docs/UPGRADEGUIDE.md
Fixing some typos in our upgrade guides
> Fix upgrade typos

- packages/terra-application-header-layout/CHANGELOG.md
- packages/terra-application-header-layout/translations/en-AU.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/translations/en-AU.json
- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/translations/en-AU.json
- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/translations/en-AU.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/translations/en-AU.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/translations/en-AU.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/translations/en-AU.json
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/translations/en-AU.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/translations/en-AU.json
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/translations/en-AU.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/translations/en-AU.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/translations/en-AU.json
Added en-AU translation files Fixes #517 
@cerner/terra
> Add en-AU translations

- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/src/terra-dev-site/doc/example/PopupModalContent.jsx
Fix broken popup example.
Resolves #529
@cerner/terra
> [terra-popup] Fix broken example.

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/src/terra-dev-site/doc/disclosure-manager/UpgradeGuide.3.doc.md
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/docs/README.md
- packages/terra-modal-manager/docs/UPGRADEGUIDE.md
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/docs/README.md
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/docs/README.md
- packages/terra-slide-panel-manager/docs/UPGRADEGUIDE.md
Found a typo in one of the guides and felt it was easier to see the upgrade differences inline. If you toggle the view, you can see how the markdown renders.
Also updates a few links to point to terra-ui url
> Disclosure manager docs

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/src/terra-dev-site/doc/example/ExampleApplication.jsx
Add missing alt text to doc example image
> Add missing alt text to doc example image

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/src/terra-dev-site/doc/disclosure-manager/UpgradeGuide.3.doc.md
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/docs/UPGRADEGUIDE.md
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/docs/UPGRADEGUIDE.md
Thanks to @mjhenkes  we support diffs in our docs on dev-site! These changes I wanted to make in #532 can now be made!
> Diffs in manager docs

- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/tests/jest/__snapshots__/LayoutSlidePanel.test.jsx.snap
> Update jest snapshots

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/src/terra-dev-site/doc/example/ExampleApplicationWithNavIcons.jsx
- packages/terra-infinite-list/CHANGELOG.md
- packages/terra-infinite-list/src/terra-dev-site/doc/common/MyInitialLoadingIndicator.module.scss
- packages/terra-infinite-list/src/terra-dev-site/doc/common/MyProgressiveLoadingIndicator.module.scss
Found a few minor accessibility issues with some docs. This PR cleans up those issues.
> Fix up minor accessibility issues

- .github/CODEOWNERS
Removing Jake as a code owner
@cerner/terra
> Removing Jake as a code owner

- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/MenuItem.module.scss
> Fix menu font weight

- package.json
Update the script entry for heroku deployed builds.
@cerner/terra
> Update heroku build script.

- package.json
Update gh-pages to latest major version
> Update gh-pages to latest major version

- packages/terra-application/package.json
Forgot to update this after renaming the Application component. This component makes the most sense for the default export.
> [terra-application] Updating package.json main file location

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/StructuralTabs.module.scss
- packages/terra-tabs/src/Tabs.module.scss
Added font-weight themeable variables for mpages theme
Fixes #753
@cerner/terra
> [terra-tabs] Added font-weight themeable variables

- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/package.json
- packages/terra-application-links/src/tabs/_TabMenu.jsx
- packages/terra-application-links/src/tabs/_TabMenuDisplay.jsx
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-collapsible-menu-view/src/CollapsibleMenuView.jsx
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DateInput.jsx
- packages/terra-date-picker/src/DatePicker.jsx
- packages/terra-date-picker/src/DatePickerField.jsx
- packages/terra-date-picker/tests/jest/DateInput.test.jsx
- packages/terra-date-picker/tests/jest/DatePicker.test.jsx
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePickerField.test.jsx.snap
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/_TimeClarification.jsx
- packages/terra-date-time-picker/tests/jest/TimeClarification.test.jsx
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
- packages/terra-notification-dialog/src/NotificationDialog.jsx
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/_TabMenu.jsx
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/src/TimeInput.jsx
- packages/terra-time-input/tests/jest/TimeInput.test.jsx
- packages/terra-time-input/tests/jest/__snapshots__/TimeInput.test.jsx.snap
Reverts cerner/terra-framework#768
> Revert "[terra-framework] Updated components which interface with old React context API"

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-aggregator/src/terra-dev-site/doc/example/CustomRenderAggregatorExample.jsx
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application/CHANGELOG.md
- packages/terra-application/package.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-infinite-list/CHANGELOG.md
- packages/terra-infinite-list/package.json
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/package.json
This PR updates dev dependencies from terra-core that had new major versions.
It also normalizes dev dependency versions to mitigate lerna hoist warnings.
> Update and normalize dev dependencies

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/AbstractModal.jsx
> Fix IE10 issue with dataset

- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/src/NavigationSideMenu.jsx
- packages/terra-navigation-side-menu/src/NavigationSideMenu.module.scss
Removes visually-hidden-text styles and replaces them with terra component.
> Replace visually-hidden-text styles with component

- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/docs/MaxLengthInput.md
- packages/terra-form-validation/docs/NumericValidation.md
- packages/terra-form-validation/docs/README.md
- packages/terra-form-validation/docs/ValidationComponents.md
- packages/terra-form-validation/docs/ValidationEvents.md
- packages/terra-form-validation/src/terra-dev-site/doc/example/DefaultFormValidation.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/FormSubmitCheckboxField.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/FormSubmitDatePicker.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/FormSubmitRadioField.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/MaxLengthInput.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/NumericValidation.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationAsynchronous.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationDisableSubmit.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationOnInput.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationOnSubmit.jsx
- packages/terra-form-validation/src/terra-dev-site/doc/example/ValidationParsing.jsx
Resolves #823 
https://terra-framework-deploye-pr-824.herokuapp.com/components/terra-form-validation/form-validation/form-validation
> Add noValidate attribute to form examples

- packages/terra-disclosure-manager/CHANGELOG.md
- packages/terra-disclosure-manager/docs/README.md
> Fix Disclosure Manager README Table

- packages/terra-abstract-modal/CHANGELOG.md
- packages/terra-abstract-modal/src/AbstractModal.jsx
- packages/terra-abstract-modal/tests/wdio/abstract-modal-spec.js
> Fix issue with aria-hidden not being cleared on modal close

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
- packages/terra-date-time-picker/src/terra-dev-site/doc/guides/DateTimePickerEvents.jsx
- packages/terra-date-time-picker/tests/wdio/date-time-picker-spec.js
> Fixes JS error when losing focus from an empty date field.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/common/PopupMenuListItem.module.scss
- packages/terra-application-navigation/src/utility-menu/UtilityMenuHeaderButton.module.scss
Address no user clipping of icon and introduce border-bottom themeable variable for focus.
@cerner/terra
> [terra-application-navigation] Clip bug and add border-bottom var.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
Update icon version
Fixes #918
@cerner/terra
> Update icon version

- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
> Fix dependencies by adding terra-breakpoints

- .github/CODEOWNERS
Add Dave as a code owner
@cerner/terra
> Add Dave as a code owner

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/tests/wdio/date-picker-spec.js
Test logic for the incomplete and invalid wdio tests was causing them to fail in theming repos
Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].
Please add an entry in the CHANGELOG.md file in each package you modify.
@cerner/terra
> [terra-date-picker] Fixing test logic for incomplete and invalid tests

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/src/terra-dev-site/test/date-input/FocusBlurDateInput.test.jsx
- packages/terra-date-input/src/terra-dev-site/test/date-input/FocusBlurDateInputField.test.jsx
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerFocusBlur.test.jsx
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/terra-dev-site/doc/guides/DateTimePickerEvents.jsx
- packages/terra-date-time-picker/src/terra-dev-site/test/date-time-picker/DateTimePickerDSTBlur.test.jsx
- packages/terra-date-time-picker/src/terra-dev-site/test/date-time-picker/DateTimePickerFocusBlur.test.jsx
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/src/terra-dev-site/test/time-input/time-input/FocusBlur.test.jsx
Fixed the eslint errors regarding operator-assignment.
These errors were thrown due to the latest release of eslint v6.7.1
> [terra-framework] Fix for operator-assignment eslint error

- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/MenuItem.jsx
- packages/terra-menu/src/terra-dev-site/doc/menu/Menu.1.doc.jsx
Fixes [#2759](https://github.com/cerner/terra-core/issues/2759)
> [terra-menu]Updated Docs for title update of eIFU icon.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/ApplicationNavigation.module.scss
Update `content-layout` background-color from `white` to `transparent`.
Resolves #1037
> [terra-application-navigation] Update background color

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DatePicker.jsx
- packages/terra-date-picker/src/DatePickerField.jsx
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
Updated the props documentation to reflect the changes from https://github.com/cerner/terra-framework/pull/1045.
> [terra-date-picker][terra-date-time-picker] Prop documentation updated

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/src/terra-dev-site/doc/embedded-content-consumer/EmbeddedContentConsumer.1.doc.mdx
> [terra-embedded-content-consumer] doc typo

- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
- packages/terra-modal-manager/src/ModalManager.jsx
- packages/terra-modal-manager/src/ModalManager.module.scss
- packages/terra-modal-manager/src/clinical-lowlight-theme/ModalManager.module.scss
- packages/terra-modal-manager/src/orion-fusion-theme/ModalManager.module.scss
- packages/terra-modal-manager/tests/jest/ModalManager.test.jsx
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
- packages/terra-modal-manager/themes/clinical-lowlight-theme/clinical-lowlight-theme.scss
- packages/terra-modal-manager/themes/orion-fusion-theme/orion-fusion-theme.scss
Add theme context to terra-modal-manager.
@cerner/terra
> [terra-modal-manager] Add theme context

- package.json
- wdio.conf.js
[Terra-toolkit now provides this configuration](https://github.com/cerner/terra-toolkit-boneyard/blob/master/CHANGELOG.md#610---may-5-2020)
commit ref: https://github.com/cerner/terra-toolkit-boneyard/commit/d5407bbf1fc522b00365bb25724a5284d80de83b
Project tests.
@cerner/terra
> Update WDIO config to use default Axe Configuration

- .gitignore
Signed-off-by: Jeremy Fuksa <hello@orangefla.me>
Added `.DS_Store` to `.gitignore`.
@cerner/terra
> Ignoring .DS_Store files.

- .travis.yml
- docker-compose.yml
- package.json
- wdio.conf.js
Similarly to [terra-core#3072](https://github.com/cerner/terra-core/pull/3072) we're running tests directly on travis instead of a docker container and re-organizing the steps to be more time efficient.  
Closes #
Here's our baseline:
This PR:
@cerner/terra
> Improve build times

- .travis.yml
- RELEASE.md
- package.json
- scripts/release/gitTagMonoRepo.js
For too long only the few elite bourgeoisie were given the agency to publish modules to NPM. Today, my friends, I say no more! With this PR we, the proletariat, take back the power (to release to npm)! Do you need a module released? Don't ask, just open a PR. No one needs to merge directly to main anymore.
Here's the new process:
1. Update the versions of the components via `npm run version`
2. Update change logs to have the current date for the release of the affected components.
3. Create a Release PR, Get approvals
4. Merge PR to `main`
5. Watch main to ensure releases get pushed to npm and tagged in github appropriately
Closes #
I tested all this releasing over here on a fork:
https://github.com/mjhenkes/terra-framework …
> Democratize Releases 

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
This sets up an automated release for terra-framework
@cerner/terra
> Release terra-framework

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenuHeaderButton.test.jsx.snap
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/tests/jest/__snapshots__/Tabs.test.jsx.snap
Update jest  due to changes in icon theme https://github.com/cerner/terra-core/pull/3096
Closes #
@cerner/terra
> Update jest due to changes in icon theme.

- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-navigation-prompt/CHANGELOG.md
- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
- packages/terra-theme-provider/CHANGELOG.md
- packages/terra-theme-provider/package.json
Releasing the new notification dialog.
Closes #
@cerner/terra
> Release August 27, 2020

- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/translations/nl-BE.json
- packages/terra-notification-dialog/translations/nl.json
The nl / nl-BE translation order wasn't consistent with the other files and I wasn't paying close enough attention when I updated these. Using the original translations, I have updated these.
Fixes #1232 
- project tests
@cerner/terra
> [terra-notification-dialog] Fix nl / nl-BE translations.

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-navigation-prompt/CHANGELOG.md
- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
> Publish on 9-10-2020

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
> Updating versions for 9/16 release.

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
> Publish on 9-29-2020

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
> Publish on 10-6-2020

- babel.config.js
- package.json
- webpack.config.js
This PR validates the new webpack-config-terra alpha release for terra framework.
Closes #
Yay no more theme aggregation!
@cerner/terra
> Use new webpack-config-terra package

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
Release!
Closes #
@cerner/terra
> Release October 27, 2020

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/tests/jest/common/__snapshots__/PopupMenu.test.jsx.snap
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/tests/jest/__snapshots__/DialogModal.test.jsx.snap
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/tests/jest/__snapshots__/NavigationSideMenu.test.jsx.snap
> Update failing jest tests

- app.json
16 is EOL and I want heroku to stop emailing me about it.
Closes #
@cerner/terra
> Update Heroku Stack

- app.json
- packages/terra-hookshot/CHANGELOG.md
- packages/terra-hookshot/src/_HookshotUtils.js
- packages/terra-hookshot/tests/jest/Hookshot.test.jsx
Change Variable name to fix resize popup issue.
Closes #1344 
@cerner/terra
> [terra-hookshot] Change variable name to fix resize popup issue.

- packages/terra-layout/CHANGELOG.md
- packages/terra-layout/tests/wdio/layout-slide-panel-spec.js
Title says it all.
Closes #
@cerner/terra
> [terra-layout] Removed re-declaration of $ ignore

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/package.json
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
- packages/terra-navigation-prompt/CHANGELOG.md
- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/package.json
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/package.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
> Release February 9, 2021

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/src/utility-menu/_UtilityMenu.jsx
- packages/terra-application-navigation/tests/jest/utility-menu/UtilityMenu.test.jsx
- packages/terra-application-navigation/tests/jest/utility-menu/__snapshots__/UtilityMenu.test.jsx.snap
This fixes the regression where metadata wasn't carried forward to the utility items.
Closes #1397
@cerner/terra
> [terra-application-navigation] Add back missing meta data

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
> Release April 12, 2021

- .github/CODEOWNERS
> [terra-framework] Update CODEOWNERS

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
> Release April 27, 2021

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
Updates for release 6/1/2021
@cerner/terra
> Updates for release 6/1/2021

- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-infinite-list/CHANGELOG.md
- packages/terra-infinite-list/package.json
> Publish on 6-15-2021

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-name/CHANGELOG.md
- packages/terra-application-name/package.json
- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
> Publish on 7-6-2021

- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/package.json
- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/package.json
- packages/terra-modal-manager/CHANGELOG.md
- packages/terra-modal-manager/package.json
- packages/terra-navigation-prompt/CHANGELOG.md
- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
- packages/terra-popup/CHANGELOG.md
- packages/terra-popup/package.json
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/package.json
> Release 7/13

- lerna.json
- packages/terra-aggregator/CHANGELOG.md
- packages/terra-aggregator/package.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-navigation-prompt/CHANGELOG.md
- packages/terra-navigation-prompt/package.json
- packages/terra-notification-dialog/CHANGELOG.md
- packages/terra-notification-dialog/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
First release for @cerner/terra-framework-docs
Closes #
@cerner/terra
> Release July 20, 2021

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/modal-manager/ModalManagerWithHeaderAdapter.test.jsx
> [terra-framework-docs] Don't reference src in tests.

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
> Release July 23, 2021

- .github/CODEOWNERS
- .github/stale.yml
Add Ben to code owners and set up auto closing of issues
> Add Ben to code owners and set up auto closing of issues

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
Release on 11-02-2021.
Closes #
@cerner/terra
> Release on 11-02-2021

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-picker/src/DateInput.jsx
- packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerDefault.test.jsx
- packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerReadOnly.test.jsx
- packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerRemount.test.jsx
- packages/terra-date-picker/src/terra-dev-site/test/date-picker/MultipleDatePickerField.test.jsx
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
Set input id at the parent div instead of at each of the three inputs to prevent elements with identical id.
Closes #
@cerner/terra
> [terra-date-picker] Date input ID

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
- terra-date-input@1.32.0
- terra-date-picker@4.71.1
- terra-date-time-picker@4.72.1
- terra-dialog-modal@3.74.1
- terra-form-validation@1.69.1
- terra-time-input@4.43.1
Closes #
@cerner/terra
> Publish on 01-04-2022

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
> Publish 2-2-22

- package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
> Feb 9 2022 release

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
- terra-date-input@1.32.1
- terra-date-time-picker@4.73.0
- terra-form-validation@1.69.3
- terra-time-input@4.45.0
Closes #
@cerner/terra
> Publish on 02-15

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-pills/CHANGELOG.md
- packages/terra-pills/package.json
- @cerner/terra-framework-docs@1.7.0
- @cerner/terra-pills@1.0.0
Closes #
@cerner/terra
> Publish on 03-08-2022

- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
- terra-date-input@1.34.1
- terra-date-picker@4.73.1
- terra-date-time-picker@4.75.0
- terra-dialog-modal@3.74.4
- terra-form-validation@1.69.6
- @cerner/terra-framework-docs@1.8.1
- terra-time-input@4.46.1
Closes #
@cerner/terra
> Publish on 03-29-2022

- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-infinite-list/CHANGELOG.md
- packages/terra-infinite-list/package.json
> release prep

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/pills/FilterPills.1.doc.mdx
Super minor fixes:
- Updated import instructions for terra-pills to correct for scoped package
```diff
- import FilterPills from 'terra-pills';
+ import FilterPills, { Pill } from '@cerner/terra-pills';
```
- Updated Changelog for better consistency
> [terra-framework-docs] Fix pills doc

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
Release PR for Date-Picker ( releasing the component before the scheduled release since It had due of 07/25 by consumer team )
Closes #
@cerner/terra
> Release for Terra-Date-Picker 07/27/2022

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
- packages/terra-date-time-picker/tests/wdio/date-time-picker-spec.js
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/date-time-picker/example/DateTimePickerDST.jsx
> [terra-date-time-picker] Improve keyboard navigation when moving over the start date of DST.

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
The following components will be released:
- terra-date-time-picker: @4.77.0
- terra-framework-docs: @1.10.0
Closes #
@cerner/terra
> Release 20/09

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
The following components will be released:
terra-framework-docs: @1.11.0
Closes #
@cerner/terra
> Release 27-09-2022

- packages/terra-application-header-layout/CHANGELOG.md
- packages/terra-application-header-layout/package.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-name/CHANGELOG.md
- packages/terra-application-name/package.json
- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/package.json
Release terra-application-header-layout (06/12)
Closes #
@cerner/terra
> Release 06/12

- packages/terra-application-navigation/CHANGELOG.md
- packages/terra-application-navigation/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
- terra-application-navigation@1.61.0
- terra-date-picker@4.76.0
- terra-date-time-picker@4.79.0
- terra-dialog-modal@3.77.0
- terra-form-validation@1.72.0
- @cerner/terra-framework-docs@1.14.0
- terra-tabs@6.63.0
Closes #
@cerner/terra
> Release-07/02

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
> [terra-date-time-picker] Fix onBlur event bug

- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/package.json
The following components will be releasesd:
- terra-collapsible-menu-view@6.66.0
- @cerner/terra-framework-docs@1.18.0
- terra-slide-panel-manager@5.66.0
Closes #
@cerner/terra
> Release 05/04

- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/src/utility/_UtilityMenu.jsx
> commit for UXPLATFROM-8603

- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/Tabs.1.doc.mdx
- packages/terra-framework-docs/src/terra-dev-site/doc/tabs/example/WorkspaceExample.jsx
- packages/terra-tabs/src/Workspace.jsx
- packages/terra-tabs/src/Workspace.module.scss
- packages/terra-tabs/src/WorkspaceItem.jsx
- packages/terra-tabs/src/clinical-lowlight-theme/HiddenTab.module.scss
- packages/terra-tabs/src/clinical-lowlight-theme/Tab.module.scss
- packages/terra-tabs/src/clinical-lowlight-theme/TabDropDown.module.scss
- packages/terra-tabs/src/clinical-lowlight-theme/TabHeader.module.scss
- packages/terra-tabs/src/clinical-lowlight-theme/Workspace.module.scss
- packages/terra-tabs/src/common tabs/Tab.module.scss
- packages/terra-tabs/src/common tabs/_Tab.jsx
- packages/terra-tabs/src/common tabs/_Tabs.jsx
- packages/terra-tabs/src/orion-fusion-theme/HiddenTab.module.scss
- packages/terra-tabs/src/orion-fusion-theme/Tab.module.scss
- packages/terra-tabs/src/orion-fusion-theme/TabDropDown.module.scss
- packages/terra-tabs/src/orion-fusion-theme/TabHeader.module.scss
- packages/terra-tabs/src/orion-fusion-theme/Workspace.module.scss
- packages/terra-tabs/src/scroll-persistence.js
- packages/terra-tabs/src/usePortalManager.jsx
Created an Example for Workspace Tab.
Moving "Terra-Application" Workspace Tab to "Terra-Framework"  Terra-Tab.
[UXPLATFORM-8994](https://jira2.cerner.com/browse/UXPLATFORM-8994) 
---
@cerner/terra
> Example for Workspace Tab with Icon and Custom Display Props.

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/worklist-data-grid/About.1.doc.mdx
- packages/terra-worklist-data-grid/README.md
This PR adds a alpha phase disclaimer to the README to give consumers a heads up about potential breaking changes until the first stable release.
---
@cerner/terra
> [worklist-data-grid] Add disclaimer to readme

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/menu/example/BasicMenu.jsx
- packages/terra-menu/CHANGELOG.md
Updated example to be more accessible and realistic.
Example were confusing and unrealistic.
**Additional Details**
This PR resolves:
[UXPLATFORM-8361](https://jira2.cerner.com/browse/UXPLATFORM-8361)
> Updated menu example to be more accessible and realistic

- packages/terra-worklist-data-grid/README.md
Updated the badge to correctly display the correct version for worklist-data-grid
---
@cerner/terra
> [terra-worklist-data-grid] Fix README badge

- package-lock.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
Adding in worklist-data-grid as a dependency in the framework docs.
This was needed when we noticed that terra-ui did not have the latest worklist-data-grid package. This is because 0.x.x packages do *not* pull in minor versions automatically. We're including worklist-data-grid in the framework-docs package so it can be done automatically.
---
@cerner/terra
> [terra-framework-docs] Added worklist-data-grid as a dependency

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
Changes:
- @cerner/terra-framework-docs: 1.25.0 => 1.26.0
---
@cerner/terra
> Release July 20th, 2023

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/slide-panel/SlidePanelDocCommon.test.module.scss
- packages/terra-framework-docs/src/terra-dev-site/test/slide-panel/SlidePanelSVGToggle.test.jsx
- packages/terra-slide-panel/CHANGELOG.md
- packages/terra-slide-panel/src/SlidePanel.jsx
- packages/terra-slide-panel/tests/wdio/slide-panel-spec.js
Added check for disclosing node's focus before calling focus. If the disclosing node has undefined focus, the main node will be focused.
This is no longer reproducible within Terra using IE11 and custom example with SVGs in buttons, but this change has still been added to prevent unknown issues with undefined focus on disclosing nodes. An example was added with just an SVG with onclick which would cause the crash. With the added check, the crash no longer occurs.
Issues with SVGs and browser (IE11) crashing due to focus not being defined.
The example added to test these slide panel changes can be found under Tests -> Slide Panel -> Slide Panel SVG Toggle
Just SVG with onclick:
Before:
After:
Verified in IE11 with …
> [terra-slide-panel] Add focus check for disclosing node before focusing

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
Released Terra Tabs 7.2.0 with drag and drop feature
---
@cerner/terra
> Release Tabs 02/08

- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/src/Menu.jsx
Updated `showHeader` and `headerTitle` prop description.
- `headerTitle` description was updated to indicate the importance during responsive behaviour of menu. Ideally it is expected by user to pass in value.
-  `showHeader` description was updated to be indicate the option to toggle visibility of headertitle passed. It's value would be updated to `false` in the next MVB 
---
@cerner/terra
> [terra-menu] updated props desc

- CONTRIBUTORS.md
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/AlwaysCollapsedMenuItemsDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewStartAligned.jsx
Updated the toggle examples for `terra-collapsible-menu-view`
Updated the examples to include selectable toggles and toggles within a collapsed menu
To cover all permuations of the sub-component for screen reader testing
UXPLATFORM-9325 
---
@cerner/terra
> [terra-collapsible-menu-view] Update toggle examples

- .devcontainer/docker-compose-wdio.yml
- README.md
Updated the docker compose file for wdio tests to match the 4.0.0 release of terra-functional-testing (https://github.com/cerner/terra-toolkit/blob/main/packages/terra-functional-testing/src/docker/docker-compose.yml).
Using the dev container and running the wdio tests would not pull in the latest chrome version, causing screenshot mismatches.
---
@cerner/terra
> Update docker-compose-wdio.yml for dev containers

- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-utility/CHANGELOG.md
- packages/terra-application-utility/package.json
- packages/terra-collapsible-menu-view/CHANGELOG.md
- packages/terra-collapsible-menu-view/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-menu/CHANGELOG.md
- packages/terra-menu/package.json
- packages/terra-slide-panel-manager/CHANGELOG.md
- packages/terra-slide-panel-manager/package.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
- packages/terra-worklist-data-grid/CHANGELOG.md
- packages/terra-worklist-data-grid/package.json
The following packages were released:
- terra-application-layout@5.73.2
- terra-application-utility@2.53.0
- terra-collapsible-menu-view@6.77.0
- @cerner/terra-framework-docs@1.32.0
- terra-menu@6.75.0
- terra-slide-panel-manager@5.77.0
- terra-tabs@7.4.0
- terra-worklist-data-grid@0.4.0
---
@cerner/terra
> Release 10/08

- packages/terra-worklist-data-grid/CHANGELOG.md
This PR updates the CHANGELOG for terra-worklist-data-grid to correct some errors and so that it's accurate.
@cerner/terra
> [terra-worklist-data-grid] Fix CHANGELOG entries

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/date-picker/example/DatePickerDefault.jsx
Updated the example for date picker with isInvalid prop.
To demonstrate the usage of isInvalid prop. The isInavlid prop is used to show a red border around invalid date entered in the date input.
UXPLATFORM-9481 
---
@cerner/terra
> [terra-date-picker] Updated examples for terra date picker 

- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
- packages/terra-slide-group/CHANGELOG.md
- packages/terra-slide-group/package.json
- packages/terra-slide-group/src/Slide.jsx
- packages/terra-slide-group/src/SlideGroup.jsx
- packages/terra-slide-group/tests/jest/Slide.test.jsx
- packages/terra-slide-group/tests/jest/SlideGroup.test.jsx
- packages/terra-slide-group/tests/jest/__snapshots__/Slide.test.jsx.snap
- packages/terra-slide-group/tests/jest/__snapshots__/SlideGroup.test.jsx.snap
- packages/terra-slide-panel-manager/tests/jest/__snapshots__/SlidePanelManager.test.jsx.snap
Added VisuallyHiddenText to Slide component within SlideGroup to be conditionally visible to screen readers when the slide is nested. This text should be the aria-label of the slide (typically the title).
When using the VoiceOver screen reader, the aria-label of the initial slide in the SlideGroup was announced, but any nested slide was not announced upon being opened. This change allows the aria-label of nested slides to be announced to provide better context for screen reader users.
Tested using VoiceOver Utility version 10 (869.25) on MacOS Ventura 13.5 in Safari browser. Also tested with JAWS screen reader in Edge browser to ensure passive behavior.
**This PR …
> [terra-slide-group] Fix VoiceOver not announcing title of nested panel

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/react-datepicker/stylesheets/react_datepicker.module.scss
DatePicker responsive screen fix upon resize
While zooming through the screen datepicker was not accessible properly
UXPLATFORM-9480 
**Pre implementation.**
**Post implementation.**
https://github.com/cerner/terra-framework/assets/126875089/5c79b941-88af-4451-967e-fd1f497f8cad
---
@cerner/terra
> [terra-date-picker] Fix Responsive Resize issue

- lerna.json
- package.json
Add workspaces to project.
To keep up with NPM changes.
---
@cerner/terra
> Add Workspaces to project

- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/src/DateTimePicker.jsx
Added check for valid datetime before calling time clarification modal
Datetime format method was called on null object.
UXPLATFORM-9606 
---
@cerner/terra
> [terra-date-time-picker] Fixes issue when time transition from DST to ST

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- terra-embedded-content-consumer@3.38.0
- @cerner/terra-framework-docs@1.38.0
> Release 09/26/23

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/AlwaysCollapsedMenuItemsDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewDemo.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/collapsible-menu-view/example/CollapsibleMenuViewStartAligned.jsx
Updated `terra-collapsible-menu-view` examples with more meaningful controls and control labels.
To make the examples more realistic and to remove control labels that match ARIA roles like "button" and "menu".
UXPLATFORM-9228 
---
@cerner/terra
> [terra-collapsible-menu-view] Update examples with more meaningful controls and control labels

- .github/workflows/ci-cd.yml
This PR updates the CI & CD workflow action to allow for manual triggering of workflows. This basically adds a button that can be used to create a new job manually without having to create a PR. e.g. from [Terra UI](https://github.com/cerner/terra-ui/actions/workflows/ci-cd.yml):
This PR is identical to: https://github.com/cerner/terra-ui/pull/597
---
@cerner/terra
> Update `ci-cd.yml` to allow manual running of workflows

- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/WorklistDataGrid.jsx
- packages/terra-data-grid/src/subcomponents/RowSelectionCell.jsx
The screen reader messages were updates to account for the column header row being the first row.
The initial requirements specified that the column header row should not be accounted for when specifying the row index.  However, further research revealed that the column header row is specified as the first row by screen reader technologies.  This change ensures that our logic is in sync with industry standards.
The fix was tested by using the screen reader to verify that the appropriate row values were announced.
UXPLATFORM-9684 
---
@cerner/terra
> [terra-data-grid] Fix Row Selection Screen Reader Messages

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/src/EmbeddedContentConsumer.jsx
- packages/terra-embedded-content-consumer/tests/jest/EmbeddedContentConsumer.test.jsx
- packages/terra-embedded-content-consumer/tests/jest/__snapshots__/EmbeddedContentConsumer.test.jsx.snap
- packages/terra-embedded-content-consumer/tests/wdio/embedded-content-consumer-spec.js
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/TestingEmbeddedContent.2.doc.mdx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumerWithScrolling.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/BasicConsumerWithSrcDoc.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/CustomEventsConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/example/DataStatusConsumer.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithScrolling.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithSrcdoc.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/CustomEventConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/CustomEventsConsumer.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/DataStatusConsumer.test.jsx
Add title prop to the component so that it's face up and easier to set the title of the content in the frame
Add title prop to the component so consumer can easily set the title of the iframe
For better accessibility, having a title text of the content in the frame is critical. This change is to make setting the title easier.
The change can also be tested by inspecting the source code by looking for the `title` attribute for the `<iframe>` using the examples site: https://engineering.cerner.com/terra-framework/pull/1776.
VoiceOver announcing the title of the frame:
https://github.com/cerner/terra-framework/assets/3170314/01c0088d-9dbf-4255-95ae-f697350dc482
JAWS …
> [terra-embedded-content-consumer] Add title prop to component so that title can be easily set into the frame

- package-lock.json
After the compact interactive list component was pushed to main branch it causes build failures. 
This PR adds `compact interactive list component` to the package-lock file to fix that issue. Here is a screenshot of what changed in package-lock.json:
Tested locally by running `npm run clean`, then `npm ci`:
> Add compact-interactive-list to package-lock

- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/src/DateInput.jsx
- packages/terra-date-picker/tests/jest/__snapshots__/DateInput.test.jsx.snap
- packages/terra-date-picker/tests/jest/__snapshots__/DatePicker.test.jsx.snap
- packages/terra-date-picker/translations/de.json
- packages/terra-date-picker/translations/en-AU.json
- packages/terra-date-picker/translations/en-CA.json
- packages/terra-date-picker/translations/en-GB.json
- packages/terra-date-picker/translations/en-US.json
- packages/terra-date-picker/translations/en.json
- packages/terra-date-picker/translations/es-ES.json
- packages/terra-date-picker/translations/es-US.json
- packages/terra-date-picker/translations/es.json
- packages/terra-date-picker/translations/fr-FR.json
- packages/terra-date-picker/translations/fr.json
- packages/terra-date-picker/translations/nl-BE.json
- packages/terra-date-picker/translations/nl.json
- packages/terra-date-picker/translations/pt-BR.json
- packages/terra-date-picker/translations/pt.json
- packages/terra-date-picker/translations/sv-SE.json
- packages/terra-date-picker/translations/sv.json
Added hot key instruction for SR response.
This provides information to the user to be able to interact with date-picker using T,+,- keys.
---
@cerner/terra
> [terra-date-picker] Updated SR response to include hot key suggestions

- packages/terra-slider/CHANGELOG.md
- packages/terra-slider/translations/de.json
- packages/terra-slider/translations/en-GB.json
- packages/terra-slider/translations/es.json
- packages/terra-slider/translations/fr.json
- packages/terra-slider/translations/nl.json
- packages/terra-slider/translations/pt.json
- packages/terra-slider/translations/sv.json
Add translations for Slider component
UXPLATFORM-9721
---
@cerner/terra
> [terra-slider] Add translations for Slider component

- packages/terra-framework-docs/CHANGELOG.md
This PR correct some recent entries in the CHANGELOG that were caused by merge conflicts and to remove any disparencies from main.
**main branch**
**release**
`terra-data-grid` CHANGELOG was verified to be correct.
---
@cerner/terra
> [terra-framework-docs] CHANGELOG corrections

- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/src/common-tabs/_Tabs.jsx
Added check if tab label has changed.
Fixes issue where tab label fails to get updated due to having the same key before and after tab label update.
UXPLATFORM-9797 
---
@cerner/terra
> [terra-tabs] Fixes tab label update

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/package.json
- packages/terra-embedded-content-consumer/src/EmbeddedContentConsumer.jsx
- packages/terra-embedded-content-consumer/src/EmbeddedContentConsumer.module.scss
- packages/terra-embedded-content-consumer/src/ProviderIframe.module.scss
- packages/terra-embedded-content-consumer/tests/jest/EmbeddedContentConsumer.test.jsx
- packages/terra-embedded-content-consumer/tests/jest/__snapshots__/EmbeddedContentConsumer.test.jsx.snap
- packages/terra-embedded-content-consumer/translations/de.json
- packages/terra-embedded-content-consumer/translations/en-AU.json
- packages/terra-embedded-content-consumer/translations/en-CA.json
- packages/terra-embedded-content-consumer/translations/en-GB.json
- packages/terra-embedded-content-consumer/translations/en-US.json
- packages/terra-embedded-content-consumer/translations/en.json
- packages/terra-embedded-content-consumer/translations/es-ES.json
- packages/terra-embedded-content-consumer/translations/es-US.json
- packages/terra-embedded-content-consumer/translations/es.json
- packages/terra-embedded-content-consumer/translations/fr-FR.json
- packages/terra-embedded-content-consumer/translations/fr.json
- packages/terra-embedded-content-consumer/translations/nl-BE.json
- packages/terra-embedded-content-consumer/translations/nl.json
- packages/terra-embedded-content-consumer/translations/pt-BR.json
- packages/terra-embedded-content-consumer/translations/pt.json
- packages/terra-embedded-content-consumer/translations/sv-SE.json
- packages/terra-embedded-content-consumer/translations/sv.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithInvalidSrc.test.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/embedded-content-consumer/consumers/BasicConsumerWithUnframeableSrc.test.jsx
Added screenreader support to announce context of embedded iframe content
Added visually hidden text before and after the iframe wrapper.
To provide additional context to screen reader users on when the embedded content will begin and end.
https://github.com/cerner/terra-framework/assets/37230460/5c2a2ea0-3ec0-4e69-b69c-fe8782409efa
https://github.com/cerner/terra-framework/assets/37230460/5486ebf5-f73f-420c-a45f-f5d97ec2ae22
https://github.com/cerner/terra-framework/assets/37230460/00fa3fa7-1cd3-4e98-8105-41e618d8b252
https://github.com/cerner/terra-framework/assets/37230460/2f7b6a85-bfd2-4e27-9430-5b71c7b19a37
UXPLATFORM-9528 
---
Thank you …
> [terra-embedded-content-consumer] Add screenreader support to announce context of embedded iframe content

- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/DataGrid.jsx
Fixed pinned column divider issue during keyboard resize.
The grid was not being properly resized once the maximum column width was reached.
N/A
UXPLATFORM-9810 
---
@cerner/terra
> [terra-data-grid] Fixed pinned column divider issue

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/src/EmbeddedContentConsumer.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/EmbeddedContentConsumer.1.doc.mdx
Add a section around accessibility for the Embedded Content Consumer
Documentation update to include accessibility guidance
Provide guidance on the implementation to support accessibility guideline
UXPLATFORM-8572
---
@cerner/terra
> [terra-embedded-content-consumer] Update documentation to include accessibility guidance

- package-lock.json
- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-tabs/CHANGELOG.md
- packages/terra-tabs/package.json
- terra-embedded-content-consumer@3.41.0
- @cerner/terra-framework-docs@1.48.0
- terra-tabs@7.13.0
---
@cerner/terra
> Release 29-11-2023

- packages/terra-embedded-content-consumer/CHANGELOG.md
- packages/terra-embedded-content-consumer/src/EmbeddedContentProviderTestTemplate.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/BasicProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/BasicProviderWithScrolling.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/CustomEventProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/CustomEventsProvider.provider.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/embedded-content-consumer/providers/DataStatusProvider.provider.jsx
Fix XFC Provider initialization in the examples to resolve the file/path not found when building within terra-ui repo.
Initialize XFC Provider in each of the provider file.
Resolve a build issue when building in terra-ui repo.
Visual inspection of existing examples and tests to ensure they're still working as expected. Re-run all existing tests.
UXPLATFORM-9772 
Related to the initial PR https://github.com/cerner/terra-framework/pull/1874
---
@cerner/terra
> [terra-embedded-content-consumer] Update XFC Provider initialization for the examples in Embedded Content Consumer

- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/src/DataGrid.jsx
- packages/terra-data-grid/src/WorklistDataGrid.jsx
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/table/Examples/TableColumnStates.jsx
- packages/terra-framework-docs/src/terra-dev-site/test/data-grid/worklist-data-grid/DefaultWorklistDataGrid.test.jsx
- packages/terra-table/CHANGELOG.md
- packages/terra-table/src/Table.jsx
- packages/terra-table/src/subcomponents/Section.jsx
The logic was updated to prevent unnecessary rerenders in our table and grid components.
The change was made to improve performance.
N/A
---
@cerner/terra
> [terra-table] Prevent unnecessary rerenders

- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/DayMonthYearDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/HideRequiredDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/IncompleteDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/InlineDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/MonthDayYearDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/OptionalDateInputField.jsx
- packages/terra-framework-docs/src/terra-dev-site/doc/date-input/example/RequiredDateInputField.jsx
Add contextual error message.
Provide contextual text to the legend to describe the functionality of fields.
Add contextual error message.
Provide contextual text to the legend to describe the functionality of fields.
UXPLATFORM-10102
UXPLATFORM-10103
UXPLATFORM-10105 
Before Implemetation:- 
After Implementation:- 
5-9ce6-f389be0be516">
---
@cerner/terra
> Updated the examples with better label and messages

- package-lock.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/src/utils/utils.js
Fixed MPages page level error on cell select
Spread the array when creating a new one.
Earlier implementation causing page level error in MPages.
UXPLATFORM-10173 
---
@cerner/terra
> [terra-compact-interactive-list] Fixed MPages page level error on cell select

- package-lock.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
The foll components were released 
Changes:
- terra-compact-interactive-list: 1.1.1
- @cerner/terra-framework-docs: 1.61.0
---
@cerner/terra
> Release Compact Interactive List 25/01

- packages/terra-compact-interactive-list/tests/jest/CompactInteractiveList.test.jsx
- packages/terra-compact-interactive-list/tests/jest/__snapshots__/CompactInteractiveList.test.jsx.snap
- packages/terra-compact-interactive-list/tests/jest/utils.test.jsx
**This PR is a part of ****
UXPLATFORM-10173
> Compact interactive list converseColumns tests added

- package-lock.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- terra-compact-interactive-list@1.2.0
- @cerner/terra-framework-docs@1.62.0
> Release compact interactive list docs and tests enhancements

- packages/terra-folder-tree/CHANGELOG.md
- packages/terra-folder-tree/translations/de.json
- packages/terra-folder-tree/translations/en-GB.json
- packages/terra-folder-tree/translations/es.json
- packages/terra-folder-tree/translations/fr.json
- packages/terra-folder-tree/translations/nl.json
- packages/terra-folder-tree/translations/pt.json
- packages/terra-folder-tree/translations/sv.json
> Adding translations for folder-tree

- .github/workflows/ci-cd.yml
This PR temporarily disables the wdio test step due to random failures in order to get a release done. This will be reverted after the release.
---
@cerner/terra
> Temporarily disable wdio tests

- package-lock.json
- packages/terra-abstract-modal/tests/jest/__snapshots__/AbstractModal.test.jsx.snap
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
This PR updates Jest snapshots to fix the breaking build.
---
@cerner/terra
> updated jest snapshots

- .github/workflows/ci-cd.yml
This reverts commit e119ea3b3d22c0b335ed7338189ff1206d3c7096.
This PR restores the temporarily removed wdio tests from the CICD.
---
@cerner/terra
> Revert "Temporarily disable wdio tests (#2037)"

- package-lock.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-date-input/CHANGELOG.md
- packages/terra-date-input/package.json
- packages/terra-date-picker/CHANGELOG.md
- packages/terra-date-picker/package.json
- packages/terra-date-time-picker/CHANGELOG.md
- packages/terra-date-time-picker/package.json
- packages/terra-dialog-modal/CHANGELOG.md
- packages/terra-dialog-modal/package.json
- packages/terra-form-validation/CHANGELOG.md
- packages/terra-form-validation/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-navigation-side-menu/CHANGELOG.md
- packages/terra-navigation-side-menu/package.json
- packages/terra-time-input/CHANGELOG.md
- packages/terra-time-input/package.json
- terra-application-layout@5.82.0
- terra-date-input@1.52.0
- terra-date-picker@4.99.0
- terra-date-time-picker@4.107.0
- terra-dialog-modal@3.103.0
- terra-form-validation@1.99.0
- @cerner/terra-framework-docs@1.67.0
- terra-navigation-side-menu@2.50.0
- [terra-time-input@4.63.0](mailto:terra-time-input@4.63.0)
---
@cerner/terra
> release-22-2-24

- packages/terra-abstract-modal/tests/jest/__snapshots__/AbstractModal.test.jsx.snap
- packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
The main branch build was failing due to outdated snapshots
> jest snapshots updated

- package-lock.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/package.json
- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-table/CHANGELOG.md
- packages/terra-table/package.json
- terra-compact-interactive-list@1.6.0
- terra-data-grid@1.16.0
- @cerner/terra-framework-docs@1.69.0
- terra-table@5.9.0
> Release Feb 28, 2024 Data Grid column actions

- packages/terra-data-grid/README.md
- packages/terra-framework-docs/src/terra-dev-site/doc/data-grid/WorklistDataGrid.1/About.2.doc.mdx
> removing alpha release warning from worklist

- package-lock.json
- packages/terra-application-layout/CHANGELOG.md
- packages/terra-application-layout/package.json
- packages/terra-application-links/CHANGELOG.md
- packages/terra-application-links/package.json
- packages/terra-compact-interactive-list/CHANGELOG.md
- packages/terra-compact-interactive-list/package.json
- packages/terra-data-grid/CHANGELOG.md
- packages/terra-data-grid/package.json
- packages/terra-framework-docs/CHANGELOG.md
- packages/terra-framework-docs/package.json
- packages/terra-table/CHANGELOG.md
- packages/terra-table/package.json
- terra-application-layout@5.91.0
- terra-application-links@6.81.0
- terra-compact-interactive-list@1.17.0
- terra-data-grid@1.27.0
- @cerner/terra-framework-docs@1.81.0
- terra-table@5.20.0
---
@cerner/terra
> Release 15/04

- packages/terra-framework-docs/src/terra-dev-site/doc/data-grid/WorklistDataGrid.1/Examples.3/WorklistDataGridColumnStates.4.doc.mdx
- packages/terra-framework-docs/src/terra-dev-site/doc/table/Examples/SortableTable.3.doc.mdx
> adding notice about sort order announcement
